"""
Django settings for victual_Menu project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-&lz)6!t2ikt-q!3zd*na=dxotv(cu^v#%ua*&(z-za318*^e*l'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# 🎯 Update this block inside your victual_Menu/settings.py file
# 🎯 ALLOW DJANGO TO ACCEPT ANY SUBDOMAINS RUNNING ON LOCALHOST:
# 🎯 ALLOW DJANGO TO ACCEPT BOTH LOCALHOST SUBDOMAINS AND NGROK TUNNELS:
# ==============================================================================
# 🌐 SECURITY MATRIX & DOMAIN BOUNDARY CONTROL NODES
# ==============================================================================

ALLOWED_HOSTS = [
    '127.0.0.1',
    'localhost',
    '.localhost',  # 🟢 Handles subdomains locally (e.g., school.localhost:8000)
    'ngrok-free.dev',
    '.ngrok-free.dev',  # 🟢 Handles external subdomains via active live ngrok test tunnel
    'corex.ng',
    '.corex.ng'  # 🟢 Automatically allows INFINITE subdomains across the whole corex network!
]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'menu',
     'modern',
    'advance2',
    'super_admin',
    'modern3',
    'modern4',
    'modern5',
    'modern6',
    'modern7'
]

# 🎯 INJECT THIS CUSTOM ROUTER ENGINE INSIDE YOUR settings.py MIDDLEWARE ARRAY:

# ==============================================================================
# 🌐 GLOBAL COREX MIDDLEWARE MANAGEMENT SYSTEM TRACKS
# ==============================================================================
# ==============================================================================
# 🌐 GLOBAL COREX SYSTEM MIDDLEWARE PIPELINES
# ==============================================================================

MIDDLEWARE = [
    # 🌐 POSITION #1: CAPTURES RAW CUSTOM SUBDOMAINS INSTANTLY BEFORE COMMONMIDDLEWARE
    'super_admin.middleware.MultiTenantSubdomainRouterMiddleware',
        'whitenoise.middleware.WhiteNoiseMiddleware',
    # Standard Internal Django Security & Framework Layers Follow Below Safely
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',

    # Commented out clean code archive for system housekeeping
    # 'super_admin.middleware.CorexUniversalSubdomainRouterMiddleware',

    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'victual_Menu.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'victual_Menu.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}

# ==============================================================================
# 🎨 ABSOLUTE FINAL PRODUCTION STATIC ASSET Blueprints
# ==============================================================================
import os

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

LOGOUT_REDIRECT_URL = '/'

STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

# 🟢 THE INSTANT MANIFEST FIX: Tells WhiteNoise to ignore missing map files!
WHITENOISE_MANIFEST_STRICT = False
