# Generated by Django 6.1 on 2026-09-05 01:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('super_admin', '0007_platformsetting_platform_logo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Modern6AgencyStoreFront',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brokerage_email', models.EmailField(default='brokerage@corex.ng', max_length=254)),
                ('brokerage_hotline', models.CharField(default='+234 (0) 900 800 7000', max_length=30)),
                ('office_physical_address', models.CharField(default='Block 10, Admiralty Way, Lekki Phase 1, Lagos, Nigeria', max_length=255)),
                ('agency_logo', models.ImageField(blank=True, null=True, upload_to='modern6_agency_logos/')),
                ('hero_headline_title', models.CharField(default='Find Your Dream Safe Haven & Luxury Space', max_length=255)),
                ('hero_subheadline_copy', models.TextField(default='Discover premium architectural masterpieces, high-tier residential structures, and secure real estate investment portfolios across Nigeria.')),
                ('count_properties_sold', models.IntegerField(default=145)),
                ('count_active_listings', models.IntegerField(default=38)),
                ('count_verified_brokers', models.IntegerField(default=12)),
                ('initialized_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'modern6 Agency Store Profile',
                'verbose_name_plural': 'modern6 Agency Store Profiles',
                'ordering': ['-initialized_at'],
            },
        ),
        migrations.CreateModel(
            name='Modern6PropertyCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100, verbose_name='Category/House Type Title')),
                ('category_slug', models.SlugField(help_text='e.g., luxury-villa, penthouse', max_length=120)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agency_categories', to='modern6.modern6agencystorefront')),
            ],
            options={
                'verbose_name': 'modern6 Property Category Slot',
                'verbose_name_plural': 'modern6 Property Category Slots',
                'unique_together': {('store', 'category_slug')},
            },
        ),
        migrations.CreateModel(
            name='Modern6PropertyListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_title', models.CharField(max_length=150, verbose_name='Property Title')),
                ('location_city', models.CharField(default='Lekki, Lagos', help_text='e.g., Miami, Florida or Lekki, Lagos', max_length=120)),
                ('price_numeric', models.DecimalField(decimal_places=2, default=25000000.0, help_text='For behind-the-scenes filtering operations', max_digits=12)),
                ('price_display_label', models.CharField(default='₦25M - ₦50M', help_text='e.g., $800k - $2M or ₦25M - ₦50M', max_length=100)),
                ('property_thumbnail', models.ImageField(help_text='Upload property card render mockup picture', upload_to='modern6_properties/')),
                ('ambient_glow_color', models.CharField(choices=[('glow-orange', 'Radiant Sunset Orange Glow'), ('glow-blue', 'Electric Cyan Blue Glow'), ('glow-purple', 'Cyber Neon Purple Glow')], default='glow-orange', max_length=30)),
                ('dynamic_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='listed_houses', to='modern6.modern6propertycategory', verbose_name='House Type Category')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agency_properties', to='modern6.modern6agencystorefront')),
            ],
            options={
                'verbose_name': 'modern6 Property Listing Card',
                'verbose_name_plural': 'modern6 Property Listing Cards',
            },
        ),
        migrations.CreateModel(
            name='Modern6RealEstateTenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agency_name', models.CharField(max_length=120, unique=True, verbose_name='Real Estate Agency Name')),
                ('agency_slug', models.SlugField(help_text='e.g., deluxe-homes', max_length=120, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_agent', models.ForeignKey(blank=True, help_text='The field agent tracking this premium real estate profile registry', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modern6_onboarded_agencies', to='super_admin.agentprofile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User Account')),
            ],
            options={
                'verbose_name': 'modern6 Property Tenant',
                'verbose_name_plural': 'modern6 Property Tenants',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='modern6agencystorefront',
            name='tenant_identity',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agency_profile', to='modern6.modern6realestatetenant', verbose_name='SaaS Identity Link'),
        ),
        migrations.CreateModel(
            name='Modern6TourAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=120)),
                ('client_email', models.EmailField(max_length=254)),
                ('client_phone', models.CharField(max_length=30)),
                ('requested_location', models.CharField(max_length=150)),
                ('requested_house_type', models.CharField(max_length=100)),
                ('requested_price_range', models.CharField(max_length=100)),
                ('tour_date', models.CharField(help_text='Tour scheduling date picked from front deck', max_length=100)),
                ('client_message', models.TextField(blank=True, verbose_name='Additional Brief Notes')),
                ('is_confirmed', models.BooleanField(default=False, verbose_name='Processed / Booked')),
                ('logged_at', models.DateTimeField(auto_now_add=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agency_tours', to='modern6.modern6agencystorefront')),
            ],
            options={
                'verbose_name': 'modern6 Property Tour Booking',
                'verbose_name_plural': 'modern6 Property Tour Bookings',
                'ordering': ['-logged_at'],
            },
        ),
    ]
