# Generated by Django 6.1 on 2026-09-05 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modern6', '0002_modern6agencystorefront_hero_background_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modern6agencystorefront',
            name='hero_background_image',
        ),
    ]
