# Generated by Django 6.1 on 2026-09-05 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modern6', '0003_remove_modern6agencystorefront_hero_background_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='modern6agencystorefront',
            name='hero_background_image',
            field=models.ImageField(blank=True, help_text='Upload the premium hero cockpit background graphic (will render at upper section only)', null=True, upload_to='modern6_hero_bg/'),
        ),
    ]
