# Generated by Django 6.1 on 2026-09-05 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modern6', '0005_remove_modern6agencystorefront_hero_background_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='modern6propertylisting',
            name='property_details_text',
            field=models.TextField(default='Premium architectural luxury asset equipped with modern high-tier residential structures and secure property parameters.', help_text='Write out the full description details for this house card to display on its detail page.', verbose_name='Detailed Property Description'),
        ),
    ]
