# Generated by Django 6.1 on 2026-09-28 22:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modern11', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modern11salonstorefront',
            name='tenant_identity',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='studio_profile', to='modern11.modern11salontenant', verbose_name='SaaS Identity Link'),
        ),
    ]
