# Generated by Django 6.1 on 2026-09-29 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modern11', '0002_alter_modern11salonstorefront_tenant_identity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modern11SalonProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(help_text='e.g. Matte Crimson Red Lipstick', max_length=150, verbose_name='Product Brand & Name')),
                ('product_category', models.CharField(choices=[('PERFUME', 'Exotic Perfumes / Scents'), ('HAIR', 'Premium Hair Bundles / Weaves'), ('LIPSTICK', 'Lipsticks / Lip Gloss'), ('EYELASH', 'Eyelashes / Eye Enhancements'), ('OTHER', 'General Cosmetics & Care')], default='OTHER', max_length=20, verbose_name='Product Category Group')),
                ('product_price', models.DecimalField(decimal_places=2, default=0.0, help_text='Retail selling fee in Naira', max_digits=12)),
                ('product_image', models.ImageField(help_text='Upload a crisp, high-resolution product picture', upload_to='modern11_shop/')),
                ('product_description', models.TextField(default='Premium salon-grade quality checked and approved.', verbose_name='Product Description / Details')),
                ('is_featured_on_home', models.BooleanField(default=False, help_text='Check this box to push this retail item directly to your index page view layout.', verbose_name='Showcase on Home Page Product Sliders')),
                ('is_in_stock', models.BooleanField(default=True, verbose_name='Item Is Available In Stock Grid')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salon_products', to='modern11.modern11salonstorefront')),
            ],
            options={
                'verbose_name': 'modern11 Salon Shop Product',
                'verbose_name_plural': 'modern11 Salon Shop Products',
                'ordering': ['-created_at'],
            },
        ),
    ]
