# Generated by Django 6.1 on 2026-09-17 12:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('super_admin', '0010_alter_domainengine_app_target'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Modern9ApparelCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100, verbose_name='Category Name')),
                ('category_slug', models.SlugField(help_text='e.g., men-apparel, active-women', max_length=120)),
                ('category_image', models.ImageField(blank=True, help_text='Upload grid display banner', null=True, upload_to='modern9_categories/')),
            ],
            options={
                'verbose_name': 'modern9 Apparel Category Slot',
                'verbose_name_plural': 'modern9 Apparel Category Slots',
            },
        ),
        migrations.CreateModel(
            name='Modern9ApparelStoreFront',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_email', models.EmailField(default='support@tailstore.corex.ng', max_length=254)),
                ('store_hotline', models.CharField(default='+234 (0) 800 900 1000', max_length=30)),
                ('store_hq_address', models.CharField(default='123 Street Name, Lagos, Nigeria', max_length=255)),
                ('store_logo_text', models.CharField(default='TailStore', max_length=50)),
                ('hero_title_accent', models.CharField(default='Women', max_length=100)),
                ('hero_description_copy', models.TextField(default='Experience the best in sportswear with our latest collection.')),
                ('hero_slide_image', models.ImageField(blank=True, null=True, upload_to='modern9_heros/')),
                ('promo_headline', models.CharField(default='Welcome to Our Shop', max_length=255)),
                ('promo_background_image', models.ImageField(blank=True, null=True, upload_to='modern9_promos/')),
                ('brand_logo_1', models.ImageField(blank=True, null=True, upload_to='modern9_brands/', verbose_name='Brand Logo 1 (e.g. PHP)')),
                ('brand_logo_2', models.ImageField(blank=True, null=True, upload_to='modern9_brands/', verbose_name='Brand Logo 2 (e.g. React)')),
                ('brand_logo_3', models.ImageField(blank=True, null=True, upload_to='modern9_brands/', verbose_name='Brand Logo 3 (e.g. Tailwind)')),
                ('brand_logo_4', models.ImageField(blank=True, null=True, upload_to='modern9_brands/', verbose_name='Brand Logo 4 (e.g. TS)')),
                ('brand_logo_5', models.ImageField(blank=True, null=True, upload_to='modern9_brands/', verbose_name='Brand Logo 5 (e.g. HTML5)')),
                ('brand_logo_6', models.ImageField(blank=True, null=True, upload_to='modern9_brands/', verbose_name='Brand Logo 6 (e.g. JS)')),
                ('initialized_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'modern9 Apparel Store Profile',
                'verbose_name_plural': 'modern9 Apparel Store Profiles',
                'ordering': ['-initialized_at'],
            },
        ),
        migrations.CreateModel(
            name='Modern9ApparelProductListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_title', models.CharField(max_length=150, verbose_name='Product Item Title')),
                ('current_price', models.DecimalField(decimal_places=2, default=29.99, help_text='Active retail price tag', max_digits=12)),
                ('old_slashed_price', models.DecimalField(blank=True, decimal_places=2, help_text='Optional cross-out original price (e.g. $49.99)', max_digits=12, null=True)),
                ('product_thumbnail', models.ImageField(help_text='Upload crisp product thumbnail picture', upload_to='modern9_products/')),
                ('product_details_text', models.TextField(default='Premium retail quality apparel crafted with elite fabric strands.')),
                ('is_popular', models.BooleanField(default=False, verbose_name='Display in Popular Products Grid')),
                ('is_latest', models.BooleanField(default=True, verbose_name='Display in Latest Products Grid')),
                ('is_in_stock', models.BooleanField(default=True, verbose_name='Available for Dispatch')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dynamic_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='listed_apparel', to='modern9.modern9apparelcategory', verbose_name='Garment Type Category')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_products', to='modern9.modern9apparelstorefront')),
            ],
            options={
                'verbose_name': 'modern9 Apparel Product Listing Card',
                'verbose_name_plural': 'modern9 Apparel Product Listing Cards',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Modern9ApparelNewsletterLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscriber_email', models.EmailField(max_length=254)),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_subscribers', to='modern9.modern9apparelstorefront')),
            ],
            options={
                'verbose_name': 'modern9 Newsletter Lead',
                'verbose_name_plural': 'modern9 Newsletter Leads',
                'ordering': ['-subscribed_at'],
            },
        ),
        migrations.AddField(
            model_name='modern9apparelcategory',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_categories', to='modern9.modern9apparelstorefront'),
        ),
        migrations.CreateModel(
            name='Modern9ApparelBlogArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_title', models.CharField(max_length=250, verbose_name='Magazine Article Title')),
                ('article_excerpt', models.TextField(default='Explore the hottest style trends of the active design season.')),
                ('article_thumbnail', models.ImageField(upload_to='modern9_blogs/')),
                ('published_date', models.DateField(auto_now_add=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_blogs', to='modern9.modern9apparelstorefront')),
            ],
            options={
                'verbose_name': 'modern9 Studio Blog Post',
                'verbose_name_plural': 'modern9 Studio Blog Posts',
                'ordering': ['-published_date'],
            },
        ),
        migrations.CreateModel(
            name='Modern9ApparelTenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=120, unique=True, verbose_name='Apparel Brand Name')),
                ('brand_slug', models.SlugField(help_text='e.g., tailstore-lekki, urban-threads', max_length=120, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modern9_onboarded_shops', to='super_admin.agentprofile', verbose_name='Assigned Field Agent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Store Owner Account')),
            ],
            options={
                'verbose_name': 'modern9 Apparel Tenant',
                'verbose_name_plural': 'modern9 Apparel Tenants',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='modern9apparelstorefront',
            name='tenant_identity',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='store_profile', to='modern9.modern9appareltenant', verbose_name='SaaS Identity Link'),
        ),
        migrations.AlterUniqueTogether(
            name='modern9apparelcategory',
            unique_together={('store', 'category_slug')},
        ),
    ]
