# Generated by Django 6.1 on 2026-09-22 13:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('super_admin', '0012_alter_domainengine_app_target'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Modern10CarCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100, verbose_name='Category Type Title')),
                ('category_slug', models.SlugField(help_text='e.g., luxury-suvs, tokunbo-sedans', max_length=120)),
            ],
            options={
                'verbose_name': 'modern10 Car Category Slot',
                'verbose_name_plural': 'modern10 Car Category Slots',
            },
        ),
        migrations.CreateModel(
            name='Modern10CarStoreFront',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_email', models.EmailField(default='info@corexautos.ng', max_length=254)),
                ('contact_phone', models.CharField(default='+234 (0) 803 456 7891', max_length=30)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='modern10_logos/')),
                ('hero_title', models.CharField(default='Mercedes-Benz G63 AMG', max_length=255)),
                ('hero_subtitle', models.TextField(default='Find, Book, and Rent Car in Easy Steps')),
                ('hero_banner_image', models.ImageField(blank=True, null=True, upload_to='modern10_heros/')),
                ('about_headline', models.CharField(default='We Provide Everything You Need For Ultimate Mobility', max_length=255)),
                ('about_description_copy', models.TextField(default="Operating heavy-duty multi-tenant logistics across Nigeria's economic hubs requires strict technical discipline.")),
                ('why_choose_us_intro', models.TextField(default='We provide verified documentation, secure payment gateways, and highly vetted drivers for all car rentals.', verbose_name='Why Choose Us Description')),
                ('pillar_1_title', models.CharField(default='100% Verified Custom Duty & Tokunbo Clearance Papers', max_length=100)),
                ('pillar_2_title', models.CharField(default='Real-time GPS Fleet Surveillance & Telemetry Support', max_length=100)),
                ('pillar_3_title', models.CharField(default='Comprehensive Insurance Coverage on All Operational Leases', max_length=100)),
                ('pillar_4_title', models.CharField(default='Verified Ownership Transfers and Stress-free Registration', max_length=100)),
                ('initialized_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'modern10 Car Store Profile',
                'verbose_name_plural': 'modern10 Car Store Profiles',
                'ordering': ['-initialized_at'],
            },
        ),
        migrations.CreateModel(
            name='Modern10CarListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make_and_model', models.CharField(help_text='e.g. Mercedes-Benz G63 AMG', max_length=150, verbose_name='Vehicle Make and Model')),
                ('purpose', models.CharField(choices=[('RENT', 'For Short-Term Rental / Hire'), ('SALE', 'For Direct Purchase / Sale')], default='RENT', max_length=10, verbose_name='Listing Purpose')),
                ('rental_price_per_day', models.DecimalField(decimal_places=2, default=0.0, help_text='Daily hire fee in Naira (if purpose is Rent)', max_digits=12)),
                ('sale_price', models.DecimalField(decimal_places=2, default=0.0, help_text='Total procurement fee in Naira (if purpose is Sale)', max_digits=14)),
                ('vehicle_image', models.ImageField(help_text='Upload crisp automotive picture layout', upload_to='modern10_cars/')),
                ('year_of_manufacture', models.IntegerField(default=2024, verbose_name='Year Model')),
                ('mileage', models.CharField(default='0 km', help_text='Odometer calculation (e.g. 15,200 km)', max_length=50)),
                ('transmission_automatic', models.BooleanField(default=True, help_text='Checked = Auto, Unchecked = Manual', verbose_name='Automatic Transmission')),
                ('horsepower', models.CharField(default='300 hp', max_length=30, verbose_name='Engine Horsepower')),
                ('fuel_type', models.CharField(choices=[('PETROL', 'Petrol / Unleaded'), ('DIESEL', 'Diesel'), ('HYBRID', 'Hybrid Engine'), ('ELECTRIC', 'Electric EV Matrix')], default='PETROL', max_length=20)),
                ('seating_capacity', models.IntegerField(default=5)),
                ('vehicle_details_text', models.TextField(default='Premium design checked with multi-point diagnostics clear.', verbose_name='Car Overview / Description')),
                ('stock_reference', models.CharField(default='K99D10459', max_length=50, verbose_name='Stock Reference ID')),
                ('vin_registry', models.CharField(default='3VWKM245686NGR', max_length=50, verbose_name='VIN Registry code')),
                ('showroom_location', models.CharField(default='Lekki Phase 1, Lagos, Nigeria', max_length=255)),
                ('is_available', models.BooleanField(default=True, verbose_name='Available for Catalog Grid Display')),
                ('is_featured_on_home', models.BooleanField(default=False, verbose_name='Showcase in Home Sliders')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dynamic_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='listed_vehicles', to='modern10.modern10carcategory', verbose_name='Vehicle Segment Category')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studio_products', to='modern10.modern10carstorefront')),
            ],
            options={
                'verbose_name': 'modern10 Vehicle Fleet Listing Card',
                'verbose_name_plural': 'modern10 Vehicle Fleet Listing Cards',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='modern10carcategory',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studio_categories', to='modern10.modern10carstorefront'),
        ),
        migrations.CreateModel(
            name='Modern10CarBlogArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_title', models.CharField(max_length=250, verbose_name='Article Title')),
                ('author_display_name', models.CharField(default='Alao Chukwuma', max_length=100)),
                ('article_thumbnail', models.ImageField(upload_to='modern10_blogs/')),
                ('article_summary', models.TextField(default='Premium automotive review overview guidelines.')),
                ('article_body_content', models.TextField(default='Full journalism entry logs specifications.')),
                ('published_date', models.DateField(auto_now_add=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studio_blogs', to='modern10.modern10carstorefront')),
            ],
            options={
                'verbose_name': 'modern10 Studio Blog Post',
                'verbose_name_plural': 'modern10 Studio Blog Posts',
                'ordering': ['-published_date'],
            },
        ),
        migrations.CreateModel(
            name='Modern10CarTenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=120, unique=True, verbose_name='Automotive Business Name')),
                ('slug_name', models.SlugField(help_text='e.g., corex-autos, elite-rentals', max_length=120, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_agent', models.ForeignKey(blank=True, help_text='The field agent tracking this premium car rentals profile registry', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modern10_onboarded_studios', to='super_admin.agentprofile', verbose_name='Assigned Agent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User Account')),
            ],
            options={
                'verbose_name': 'modern10 Car Tenant',
                'verbose_name_plural': 'modern10 Car Tenants',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='modern10carstorefront',
            name='tenant_identity',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='studio_profile', to='modern10.modern10cartenant', verbose_name='SaaS Identity Link'),
        ),
        migrations.CreateModel(
            name='Modern10CarTestimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100, verbose_name='Client Name')),
                ('client_role', models.CharField(max_length=120, verbose_name='Designation/Company')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='modern10_avatars/', verbose_name='User Avatar')),
                ('quote', models.TextField(verbose_name='Testimonial Quote Statement')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studio_testimonials', to='modern10.modern10carstorefront')),
            ],
            options={
                'verbose_name': 'modern10 Car Testimonial',
                'verbose_name_plural': 'modern10 Car Testimonials',
            },
        ),
        migrations.CreateModel(
            name='Modern10NewsletterSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscriber_email', models.EmailField(max_length=254)),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studio_subscribers', to='modern10.modern10carstorefront')),
            ],
            options={
                'verbose_name': 'modern10 Newsletter Lead',
                'verbose_name_plural': 'modern10 Newsletter Leads',
                'ordering': ['-subscribed_at'],
            },
        ),
        migrations.CreateModel(
            name='Modern10StudioTeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_name', models.CharField(max_length=120, verbose_name='Full Name')),
                ('member_role', models.CharField(help_text='e.g. Director of Logistics, CEO, Sales Consultant', max_length=120, verbose_name='Corporate Designation')),
                ('member_avatar', models.ImageField(upload_to='modern10_team/', verbose_name='Profile Picture')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studio_team_members', to='modern10.modern10carstorefront')),
            ],
            options={
                'verbose_name': 'modern10 Studio Team Member Card',
                'verbose_name_plural': 'modern10 Studio Team Member Cards',
            },
        ),
        migrations.AlterUniqueTogether(
            name='modern10carcategory',
            unique_together={('store', 'category_slug')},
        ),
    ]
