# Generated by Django 6.1 on 2026-09-24 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modern10', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modern10carlisting',
            name='gallery_image_1',
            field=models.ImageField(blank=True, help_text='Optional interior view', null=True, upload_to='modern10_cars/gallery/', verbose_name='Gallery Picture 1 (Interior Cabin)'),
        ),
        migrations.AddField(
            model_name='modern10carlisting',
            name='gallery_image_2',
            field=models.ImageField(blank=True, help_text='Optional mechanical layout view', null=True, upload_to='modern10_cars/gallery/', verbose_name='Gallery Picture 2 (Engine Bay)'),
        ),
        migrations.AddField(
            model_name='modern10carlisting',
            name='gallery_image_3',
            field=models.ImageField(blank=True, help_text='Optional tail light angle view', null=True, upload_to='modern10_cars/gallery/', verbose_name='Gallery Picture 3 (Rear Profile)'),
        ),
        migrations.AddField(
            model_name='modern10carlisting',
            name='gallery_image_4',
            field=models.ImageField(blank=True, help_text='Optional dashboard/wheel custom angle view', null=True, upload_to='modern10_cars/gallery/', verbose_name='Gallery Picture 4 (Extra Details)'),
        ),
    ]
