# Generated by Django 6.1 on 2026-09-24 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modern10', '0002_modern10carlisting_gallery_image_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modern10carlisting',
            name='google_map_embed_url',
            field=models.TextField(default='https://google.com', help_text="Go to Google Maps -> Click Share -> Select Embed a map -> Copy ONLY the 'src' link text string inside the quotes (starts with https://google.com...).", verbose_name='Google Maps Iframe Embed URL Only'),
        ),
        migrations.AddField(
            model_name='modern10carlisting',
            name='vehicle_features_checklist',
            field=models.TextField(default='• Comprehensive Multi-point Diagnostic Log Clear\n• Full Synthetic Engine Oil Suite Complete\n• Keyless Entry Transponder System Ready\n• High-performance Climate Control Configuration', help_text='Insert custom features line items. Start each parameter line with a bullet point (•) or a clean hyphen (-).', verbose_name='Vehicle Features Checklist'),
        ),
    ]
