# Generated by Django 6.1 on 2026-09-24 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modern10', '0003_modern10carlisting_google_map_embed_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modern10carstorefront',
            name='why_choose_us_video_url',
            field=models.URLField(default='https://youtube.com', help_text='Paste the complete YouTube video link layout string from your address line (e.g., https://youtube.com...).', verbose_name='Why Choose Us YouTube Video URL'),
        ),
    ]
