# Generated by Django 6.1 on 2026-09-24 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modern10', '0004_modern10carstorefront_why_choose_us_video_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modern10carstorefront',
            name='why_choose_us_video_url',
        ),
    ]
