# Generated by Django 6.1 on 2026-09-24 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modern10', '0005_remove_modern10carstorefront_why_choose_us_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='modern10carstorefront',
            name='service_1_desc',
            field=models.TextField(default='Rent luxury cars easily in Lagos, Abuja, and Port Harcourt. Available for weddings, executives, and protocols.', help_text='Custom description for the first core service card row grid summary.', verbose_name='Luxury Car Rentals Service Text'),
        ),
        migrations.AddField(
            model_name='modern10carstorefront',
            name='service_2_desc',
            field=models.TextField(default='Verified Foreign Used (Tokunbo) and Brand New imports with complete custom clearance papers clearance checks verified.', help_text='Custom description for the second core service card row grid summary.', verbose_name='Buying A Vehicle Service Text'),
        ),
        migrations.AddField(
            model_name='modern10carstorefront',
            name='service_3_desc',
            field=models.TextField(default='Expert diagnostic centers with certified tracking technicians for computer programming, suspension tuning, and upgrades.', help_text='Custom description for the third core service card row grid summary.', verbose_name='Car Maintenance Service Text'),
        ),
        migrations.AddField(
            model_name='modern10carstorefront',
            name='service_4_desc',
            field=models.TextField(default='Dedicated road emergency breakdown support networks and real-time fleet surveillance telemetry across all states.', help_text='Custom description for the fourth core service card row grid summary.', verbose_name='Support 24/7 Service Text'),
        ),
    ]
