# Generated by Django 6.1 on 2026-09-24 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modern10', '0006_modern10carstorefront_service_1_desc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modern10carstorefront',
            name='feature_badge_1',
            field=models.CharField(default='V8 Engine Core', max_length=60, verbose_name='Feature Badge 1 Tag Name'),
        ),
        migrations.AddField(
            model_name='modern10carstorefront',
            name='feature_badge_2',
            field=models.CharField(default='Twin Turbo', max_length=60, verbose_name='Feature Badge 2 Tag Name'),
        ),
        migrations.AddField(
            model_name='modern10carstorefront',
            name='feature_badge_3',
            field=models.CharField(default='Climate Control', max_length=60, verbose_name='Feature Badge 3 Tag Name'),
        ),
        migrations.AddField(
            model_name='modern10carstorefront',
            name='feature_badge_4',
            field=models.CharField(default='Armored Option', max_length=60, verbose_name='Feature Badge 4 Tag Name'),
        ),
    ]
