# Generated by Django 6.1 on 2026-09-24 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modern10', '0007_modern10carstorefront_feature_badge_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modern10carstorefront',
            name='feature_desc_paragraph_1',
            field=models.TextField(default='With thousands of luxury miles navigated across active Nigerian expressways, our platform ensures seamless fleet leasing and direct ownership transfers without traditional documentation delays.', verbose_name='Feature Paragraph 1 Copy Text'),
        ),
        migrations.AddField(
            model_name='modern10carstorefront',
            name='feature_desc_paragraph_2',
            field=models.TextField(default='Every single listing undergoes standard multi-point mechanical inspections, structural integrity checks, and custom duty document clearance profiling before joining our catalog view grids.', verbose_name='Feature Paragraph 2 Copy Text'),
        ),
        migrations.AddField(
            model_name='modern10carstorefront',
            name='feature_main_headline',
            field=models.CharField(default='We Are A Trusted Name In Auto Distribution Matrix', max_length=255, verbose_name='Feature Section Headline'),
        ),
        migrations.AlterField(
            model_name='modern10carstorefront',
            name='service_1_desc',
            field=models.TextField(default='Rent luxury cars easily in Lagos, Abuja, and Port Harcourt. Available for weddings, executives, and protocols.', verbose_name='Luxury Car Rentals Service Text'),
        ),
        migrations.AlterField(
            model_name='modern10carstorefront',
            name='service_2_desc',
            field=models.TextField(default='Verified Foreign Used (Tokunbo) and Brand New imports with complete custom clearance papers clearance checks verified.', verbose_name='Buying A Vehicle Service Text'),
        ),
        migrations.AlterField(
            model_name='modern10carstorefront',
            name='service_3_desc',
            field=models.TextField(default='Expert diagnostic centers with certified tracking technicians for computer programming, suspension tuning, and upgrades.', verbose_name='Car Maintenance Service Text'),
        ),
        migrations.AlterField(
            model_name='modern10carstorefront',
            name='service_4_desc',
            field=models.TextField(default='Dedicated road emergency breakdown support networks and real-time fleet surveillance telemetry across all states.', verbose_name='Support 24/7 Service Text'),
        ),
    ]
