# Generated by Django 6.1 on 2026-09-24 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modern10', '0008_modern10carstorefront_feature_desc_paragraph_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modern10carstorefront',
            name='about_mission_text',
            field=models.TextField(default='To democratize access to premium automotive leasing and direct luxury ownership transfers across Nigeria by removing traditional documentation friction points and opaque transaction layouts entirely from the marketplace economy.', verbose_name='Our Mission Statement Text'),
        ),
        migrations.AddField(
            model_name='modern10carstorefront',
            name='about_vision_text',
            field=models.TextField(default='To establish the primary digital multi-tenant infrastructure powering vehicle procurement security, asset surveillance management, and corporate protocol coordination across West Africa with 100% processing transparency.', verbose_name='Our Vision Statement Text'),
        ),
        migrations.AddField(
            model_name='modern10carstorefront',
            name='stats_clients_count',
            field=models.CharField(default='5,100+', max_length=30, verbose_name='Counter: Happy Platform Clients'),
        ),
        migrations.AddField(
            model_name='modern10carstorefront',
            name='stats_reviews_count',
            field=models.CharField(default='1,922', max_length=30, verbose_name='Counter: Verified Dealer Reviews'),
        ),
        migrations.AddField(
            model_name='modern10carstorefront',
            name='stats_sales_count',
            field=models.CharField(default='1,500+', max_length=30, verbose_name='Counter: Successful Direct Sales'),
        ),
        migrations.AddField(
            model_name='modern10carstorefront',
            name='stats_vehicles_count',
            field=models.CharField(default='1,922', max_length=30, verbose_name='Counter: Vehicles In Stock'),
        ),
    ]
