# Generated by Django 6.1 on 2026-09-25 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modern10', '0009_modern10carstorefront_about_mission_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modern10carstorefront',
            name='facebook_url',
            field=models.URLField(blank=True, help_text='Optional profile link (e.g., https://facebook.com).', null=True, verbose_name='Merchant Facebook URL'),
        ),
        migrations.AddField(
            model_name='modern10carstorefront',
            name='instagram_url',
            field=models.URLField(blank=True, help_text='Optional profile link (e.g., https://instagram.com).', null=True, verbose_name='Merchant Instagram URL'),
        ),
        migrations.AddField(
            model_name='modern10carstorefront',
            name='twitter_url',
            field=models.URLField(blank=True, help_text='Optional profile link (e.g., https://x.com).', null=True, verbose_name='Merchant Twitter / X URL'),
        ),
    ]
