# Generated by Django 6.1 on 2026-09-04 10:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('super_admin', '0007_platformsetting_platform_logo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Modern4SlugTenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_name', models.CharField(max_length=120, unique=True, verbose_name='Hospital Name')),
                ('hospital_slug', models.SlugField(help_text='e.g., hospital', max_length=120, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_agent', models.ForeignKey(blank=True, help_text='The field agent tracking this premium hospital profile registry', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modern4_onboarded_hospitals', to='super_admin.agentprofile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User Account')),
            ],
            options={
                'verbose_name': 'modern4 SaaS Tenant',
                'verbose_name_plural': 'modern4 SaaS Tenants',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Modern4StoreFront',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_email', models.EmailField(default='desk@corex.ng', max_length=254)),
                ('emergency_phone_line', models.CharField(default='+234 (0) 800 227 3964', max_length=30)),
                ('hospital_physical_address', models.CharField(default='Plot 14, Broad Street, Lagos Island, Lagos, Nigeria', max_length=255)),
                ('operating_hours', models.CharField(default='Mon - Sat : 08:00 AM - 08:00 PM', max_length=255)),
                ('hospital_logo', models.ImageField(blank=True, help_text='Upload a square aspect ratio branding logo icon to display next to the site name header text row', null=True, upload_to='modern4_hospital_logos/')),
                ('fb_url', models.URLField(blank=True, default='https://facebook.com', null=True)),
                ('x_url', models.URLField(blank=True, default='https://x.com', null=True)),
                ('linkedin_url', models.URLField(blank=True, default='https://linkedin.com', null=True)),
                ('ig_url', models.URLField(blank=True, default='https://instagram.com', null=True)),
                ('hero_title', models.CharField(default='Good Health Is The Root Of All Happiness', max_length=500)),
                ('carousel_img_1', models.ImageField(blank=True, null=True, upload_to='modern4_carousel/')),
                ('carousel_txt_1', models.CharField(default='Cardiology', max_length=100)),
                ('carousel_img_2', models.ImageField(blank=True, null=True, upload_to='modern4_carousel/')),
                ('carousel_txt_2', models.CharField(default='Neurology', max_length=100)),
                ('carousel_img_3', models.ImageField(blank=True, null=True, upload_to='modern4_carousel/')),
                ('carousel_txt_3', models.CharField(default='Pulmonary', max_length=100)),
                ('about_main_title', models.CharField(default='Why You Should Trust Us? Get to Know About Us!', max_length=255)),
                ('about_description_primary', models.TextField(blank=True, null=True)),
                ('about_description_secondary', models.TextField(blank=True, null=True)),
                ('about_showcase_image_1', models.ImageField(blank=True, null=True, upload_to='modern4_hospital_about/')),
                ('about_showcase_image_2', models.ImageField(blank=True, null=True, upload_to='modern4_hospital_about/')),
                ('about_check_1', models.CharField(default='Quality health care services', max_length=255)),
                ('about_check_2', models.CharField(default='Only Certified & Qualified Doctors', max_length=255)),
                ('about_check_3', models.CharField(default='Medical Research Professionals', max_length=255)),
                ('about_button_text', models.CharField(default='Explore Services', max_length=100)),
                ('about_button_url', models.CharField(default='#services', max_length=255)),
                ('feature_main_headline', models.CharField(default='Why Choose Our Care Center', max_length=200)),
                ('feature_summary_text', models.TextField(blank=True, null=True)),
                ('feat_card_1_title', models.CharField(default='Certified Doctors', max_length=100)),
                ('feat_card_1_sub', models.CharField(default='Highly Experienced', max_length=100)),
                ('feat_card_2_title', models.CharField(default='Quality Services', max_length=100)),
                ('feat_card_2_sub', models.CharField(default='Premium High-End', max_length=100)),
                ('feat_card_3_title', models.CharField(default='Consultation Links', max_length=100)),
                ('feat_card_3_sub', models.CharField(default='Trusted & Secure', max_length=100)),
                ('feat_card_4_title', models.CharField(default='Dedicated Support', max_length=100)),
                ('feat_card_4_sub', models.CharField(default='24 Hours Emergency', max_length=100)),
                ('feature_banner_img', models.ImageField(blank=True, null=True, upload_to='modern4_features_panel/')),
                ('count_doctors', models.IntegerField(default=45)),
                ('count_staff', models.IntegerField(default=120)),
                ('count_patients', models.IntegerField(default=15400)),
                ('services_section_title', models.CharField(default='Health Care Solutions & Specialties', max_length=255)),
                ('team_section_title', models.CharField(default='Our Experienced Doctors', max_length=255)),
                ('appointment_title', models.CharField(default='Make An Appointment To Visit Our Doctors', max_length=255)),
                ('appointment_description', models.TextField(blank=True, null=True)),
                ('testimonial_section_title', models.CharField(default='What Our Patients Say!', max_length=255)),
                ('newsletter_subtext', models.CharField(default='Stay updated with medical infrastructure news.', max_length=255)),
                ('initialized_at', models.DateTimeField(auto_now_add=True)),
                ('tenant_identity', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hospital_profile', to='modern4.modern4slugtenant', verbose_name='SaaS Identity Link')),
            ],
            options={
                'verbose_name': 'modern4 Hospital Store Profile',
                'verbose_name_plural': 'modern4 Hospital Store Profiles',
                'ordering': ['-initialized_at'],
            },
        ),
        migrations.CreateModel(
            name='Modern4MedicalDoctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_name', models.CharField(max_length=120)),
                ('medical_title', models.CharField(help_text='e.g., Chief Medical Officer, Consultant Cardiologist', max_length=100)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='modern4_hospital_doctors/')),
                ('twitter_link', models.URLField(blank=True, default='https://twitter.com', null=True)),
                ('facebook_link', models.URLField(blank=True, default='https://facebook.com', null=True)),
                ('instagram_link', models.URLField(blank=True, default='https://instagram.com', null=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hospital_doctors', to='modern4.modern4storefront')),
            ],
            options={
                'verbose_name': 'modern4 Medical Team Doctor',
                'verbose_name_plural': 'modern4 Medical Team Doctors',
            },
        ),
        migrations.CreateModel(
            name='Modern4MedicalAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=120)),
                ('patient_email', models.EmailField(max_length=254)),
                ('patient_phone', models.CharField(max_length=30)),
                ('appointment_date', models.CharField(help_text='Date string text picked from form', max_length=100)),
                ('appointment_time', models.CharField(help_text='Time block text segment slot', max_length=100)),
                ('selected_doctor', models.CharField(max_length=120)),
                ('patient_message', models.TextField(blank=True)),
                ('is_reviewed', models.BooleanField(default=False, verbose_name='Processed / Approved')),
                ('logged_at', models.DateTimeField(auto_now_add=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hospital_appointments', to='modern4.modern4storefront')),
            ],
            options={
                'verbose_name': 'modern4 Incoming Patient Appointment',
                'verbose_name_plural': 'modern4 Incoming Patient Appointments',
                'ordering': ['-logged_at'],
            },
        ),
        migrations.CreateModel(
            name='Modern4HospitalTestimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=120)),
                ('patient_title_or_role', models.CharField(default='Patient', help_text='e.g., Recovered Patient, Local Client', max_length=100)),
                ('review_text', models.TextField()),
                ('patient_avatar', models.ImageField(blank=True, null=True, upload_to='modern4_hospital_reviews/')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hospital_testimonials', to='modern4.modern4storefront')),
            ],
            options={
                'verbose_name': 'modern4 Patient Testimonial Story',
                'verbose_name_plural': 'modern4 Patient Testimonial Stories',
            },
        ),
        migrations.CreateModel(
            name='Modern4HospitalService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=120, verbose_name='Service Title')),
                ('service_description', models.TextField(verbose_name='Service Summary Paragraph')),
                ('icon_choice', models.CharField(default='fa fa-heartbeat', help_text='Bootstrap/FontAwesome icon class name string (e.g., fa fa-heartbeat, fa fa-tooth, fa fa-brain)', max_length=50)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hospital_services', to='modern4.modern4storefront')),
            ],
            options={
                'verbose_name': 'modern4 Hospital Service Offer',
                'verbose_name_plural': 'modern4 Hospital Service Offers',
            },
        ),
        migrations.CreateModel(
            name='Modern4HospitalContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name', models.CharField(max_length=120)),
                ('sender_email', models.EmailField(max_length=254)),
                ('message_subject', models.CharField(max_length=200)),
                ('message_body', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hospital_mailbox', to='modern4.modern4storefront')),
            ],
            options={
                'verbose_name': 'modern4 Mailbox Feedback Message',
                'verbose_name_plural': 'modern4 Mailbox Feedback Messages',
                'ordering': ['-received_at'],
            },
        ),
    ]
