# Generated by Django 6.1 on 2026-08-26 12:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModernStoreFront',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=120, unique=True)),
                ('custom_slug', models.SlugField(help_text='e.g., alpha-fitness-hub', max_length=120, unique=True)),
                ('layout_theme', models.CharField(choices=[('MINIMALIST', 'Minimalist Tech Hub (Gadgets & Gear)'), ('LUXURY_DARK', 'Midnight Premium Suite (Gold & Charcoal)'), ('CREATIVE_VIBE', 'Neon Pop Creative (Streetwear & Cafes)'), ('GYM_FITNESS', 'Iron Pulse Suite (Gym Gear & Instructor Booking)')], default='MINIMALIST', max_length=25)),
                ('primary_brand_color', models.CharField(default='#000000', help_text='Hex color code for your main text headings and elements', max_length=10)),
                ('custom_hero_banner', models.ImageField(blank=True, help_text='Wide top banner backdrop graphic card', null=True, upload_to='modern_banners/')),
                ('promo_video_url', models.URLField(blank=True, help_text='Link your TikTok, YouTube showcase, or raw mp4 product display clip', null=True)),
                ('enable_video_autoplay', models.BooleanField(default=False)),
                ('enable_instructor_booking', models.BooleanField(default=False, help_text="🎯 OPTIONAL: Toggle to activate a private 'Book a Gym Instructor/Director' registration shelf for clients")),
                ('instructor_hourly_rate', models.DecimalField(decimal_places=2, default=5000.0, help_text='The consulting or personal training session booking fee baseline', max_digits=10)),
                ('whatsapp_dispatch_number', models.CharField(default='234', help_text='The WhatsApp business coordinate line for customer receipt dispatch', max_length=20)),
                ('business_biography', models.TextField(blank=True, help_text='A brief modern welcome statement, gym overview, or company mission values.')),
                ('is_premium_active', models.BooleanField(default=True)),
                ('initialized_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='modern_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Modern Store Profile',
                'verbose_name_plural': 'Modern Store Profiles',
                'ordering': ['-initialized_at'],
            },
        ),
    ]
