# Generated by Django 6.1 on 2026-08-26 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modern', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModernCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, help_text='e.g., gym-equipment', max_length=100)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modern_categories', to='modern.modernstorefront')),
            ],
            options={
                'verbose_name': 'Modern Category',
                'verbose_name_plural': 'Modern Categories',
            },
        ),
        migrations.CreateModel(
            name='ModernProductItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('brand_or_manufacturer', models.CharField(blank=True, help_text='e.g., Nike, Gymshark, Optimum Nutrition', max_length=60, null=True)),
                ('price', models.DecimalField(decimal_places=2, help_text='Set your retail price tag', max_digits=12)),
                ('image', models.ImageField(blank=True, help_text='Upload crisp, high-resolution product images', null=True, upload_to='modern_products/')),
                ('description', models.TextField(blank=True, help_text='Detailed overview layout explanation of item metrics')),
                ('unit_specification', models.CharField(blank=True, help_text='e.g., 20KG Pair, 60 Capsules, 2.2L Jug', max_length=50, null=True)),
                ('is_in_stock', models.BooleanField(default=True, verbose_name='Available for Dispatch')),
                ('product_video_embed', models.URLField(blank=True, help_text='Optional: Drop a TikTok or short video link exploring this specific item live', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modern_products', to='modern.moderncategory')),
            ],
            options={
                'verbose_name': 'Modern Product Item',
                'verbose_name_plural': 'Modern Product Items',
                'ordering': ['-created_at'],
            },
        ),
    ]
