# Generated by Django 6.1 on 2026-08-26 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modern', '0002_moderncategory_modernproductitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modernproductitem',
            name='product_video_embed',
        ),
    ]
