# Generated by Django 6.1 on 2026-08-26 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modern', '0003_remove_modernproductitem_product_video_embed'),
    ]

    operations = [
        migrations.AddField(
            model_name='modernstorefront',
            name='store_logo',
            field=models.ImageField(blank=True, help_text='Upload your official brand logo image to display directly below the store name header row', null=True, upload_to='modern_logos/'),
        ),
    ]
