# Generated by Django 6.1 on 2026-08-26 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modern', '0004_modernstorefront_store_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='modernstorefront',
            name='footer_address',
            field=models.CharField(default='Lagos, Nigeria', help_text='Physical store location address text string', max_length=255),
        ),
        migrations.AddField(
            model_name='modernstorefront',
            name='footer_phone',
            field=models.CharField(default='+234', help_text='Store contact line displayed in the footer', max_length=20),
        ),
        migrations.AddField(
            model_name='modernstorefront',
            name='instagram_username',
            field=models.CharField(blank=True, help_text='Username only (e.g., frankling_fitness)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='modernstorefront',
            name='tiktok_username',
            field=models.CharField(blank=True, help_text='TikTok handle username only', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='modernstorefront',
            name='whatsapp_link_number',
            field=models.CharField(blank=True, help_text='WhatsApp contact link phone line (e.g., 23480...)', max_length=20, null=True),
        ),
    ]
