# Generated by Django 6.1 on 2026-08-27 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modern', '0005_modernstorefront_footer_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modernstorefront',
            name='facebook_username',
            field=models.CharField(blank=True, help_text='Facebook username or page handle only', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='modernstorefront',
            name='whatsapp_link_number',
            field=models.CharField(blank=True, help_text='WhatsApp contact line (e.g., 23480...)', max_length=20, null=True),
        ),
    ]
