# Generated by Django 6.1 on 2026-08-27 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modern', '0006_modernstorefront_facebook_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modernstorefront',
            name='about_message',
            field=models.TextField(blank=True, help_text='Detailed company profile, mission statement, or store history displayed exclusively on the About Us page', null=True),
        ),
        migrations.AlterField(
            model_name='modernstorefront',
            name='business_biography',
            field=models.TextField(blank=True, help_text='Brief headline slogan displayed inside the hero banner image overlay'),
        ),
        migrations.AlterField(
            model_name='modernstorefront',
            name='whatsapp_dispatch_number',
            field=models.CharField(default='234', max_length=20),
        ),
    ]
