# Generated by Django 6.1 on 2026-08-27 20:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modern', '0007_modernstorefront_about_message_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modernstorefront',
            name='custom_slug',
        ),
        migrations.RemoveField(
            model_name='modernstorefront',
            name='store_name',
        ),
        migrations.RemoveField(
            model_name='modernstorefront',
            name='user',
        ),
        migrations.CreateModel(
            name='ModernSlugTenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=120, unique=True, verbose_name='Business Name')),
                ('custom_slug', models.SlugField(help_text='e.g., alpha-fitness-hub', max_length=120, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User Account')),
            ],
            options={
                'verbose_name': 'Modern SaaS Tenant',
                'verbose_name_plural': 'Modern SaaS Tenants',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='modernstorefront',
            name='tenant_identity',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='modern_profile', to='modern.modernslugtenant', verbose_name='SaaS Identity Link'),
            preserve_default=False,
        ),
    ]
