# Generated by Django 6.1 on 2026-08-27 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modern', '0008_remove_modernstorefront_custom_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modernstorefront',
            name='tenant_identity',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modern_profile', to='modern.modernslugtenant', verbose_name='SaaS Identity Link'),
        ),
    ]
