# Generated by Django 6.1 on 2026-08-29 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modern', '0009_alter_modernstorefront_tenant_identity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moderncategory',
            name='slug',
        ),
    ]
