# Generated by Django 6.1 on 2026-08-31 00:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modern', '0010_remove_moderncategory_slug'),
        ('super_admin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modernslugtenant',
            name='assigned_agent',
            field=models.ForeignKey(blank=True, help_text='The field agent tracking this premium user profile account registry', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modern_onboarded_vendors', to='super_admin.agentprofile'),
        ),
    ]
