# Generated by Django 6.1 on 2026-09-04 17:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('super_admin', '0007_platformsetting_platform_logo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Modern5PortfolioTenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('developer_name', models.CharField(max_length=120, unique=True, verbose_name='Developer Name')),
                ('portfolio_slug', models.SlugField(help_text='e.g., ismail-dev', max_length=120, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_agent', models.ForeignKey(blank=True, help_text='The field agent tracking this premium developer portfolio profile registry', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modern5_onboarded_portfolios', to='super_admin.agentprofile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User Account')),
            ],
            options={
                'verbose_name': 'modern5 Portfolio Tenant',
                'verbose_name_plural': 'modern5 Portfolio Tenants',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Modern5VisualDeck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_email', models.EmailField(default='developer@corex.ng', max_length=254)),
                ('contact_phone_line', models.CharField(default='+234 (0) 803 123 4567', max_length=30)),
                ('base_operation_city', models.CharField(default='Lagos, Nigeria', max_length=255)),
                ('uptime_status_label', models.CharField(default='100% STABLE — ALWAYS ALIVE', max_length=100)),
                ('developer_avatar', models.ImageField(blank=True, help_text='Upload a clean professional headshot to display inside the glowing glassmorphic circle panel', null=True, upload_to='modern5_avatars/')),
                ('github_url', models.URLField(blank=True, default='https://github.com', null=True)),
                ('linkedin_url', models.URLField(blank=True, default='https://linkedin.com', null=True)),
                ('twitter_x_url', models.URLField(blank=True, default='https://x.com', null=True)),
                ('hero_headline_text', models.CharField(default="Hello World, I'm an Expert Tech Builder Node", max_length=255)),
                ('hero_subheadline_summary', models.TextField(default='Specializing in automated database architecture sharding, multi-tenant middleware networks, and premium scalable solutions.')),
                ('ide_window_title', models.CharField(default='developer_node_specs.json', max_length=120)),
                ('ide_custom_json_writeup', models.TextField(default='{\n  "status": "Online / Open for Projects",\n  "core_stack": ["Python", "Django", "PostgreSQL"],\n  "architecture": "Clean Multi-Tenant Grid Layers"\n}', help_text='Input syntax-highlighted json lines to render inside the interactive mock code console box')),
                ('count_production_builds', models.IntegerField(default=42, help_text='Total active deployment builds completed counters.')),
                ('count_reusable_modules', models.IntegerField(default=15, help_text='Total custom core middleware plugin nodes built.')),
                ('count_happy_merchants', models.IntegerField(default=28)),
                ('initialized_at', models.DateTimeField(auto_now_add=True)),
                ('tenant_identity', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_profile', to='modern5.modern5portfoliotenant', verbose_name='SaaS Identity Link')),
            ],
            options={
                'verbose_name': 'modern5 Portfolio Store Profile',
                'verbose_name_plural': 'modern5 Portfolio Store Profiles',
                'ordering': ['-initialized_at'],
            },
        ),
        migrations.CreateModel(
            name='Modern5ProjectBentoGrid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(max_length=150, verbose_name='Project Name')),
                ('project_summary', models.TextField(verbose_name='Short Concept Overview Description')),
                ('showcase_thumbnail', models.ImageField(upload_to='modern5_portfolio_projects/')),
                ('tech_tags_csv', models.CharField(default='Django, PostgreSQL, API', help_text='Comma-separated tags list', max_length=255)),
                ('source_code_url', models.URLField(blank=True, default='https://github.com', help_text='Link to GitHub repository file path', null=True)),
                ('live_demo_url', models.URLField(blank=True, default='https://corex.ng', help_text='Link to production active demo track', null=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_projects', to='modern5.modern5visualdeck')),
            ],
            options={
                'verbose_name': 'modern5 Portfolio Bento Project',
                'verbose_name_plural': 'modern5 Portfolio Bento Projects',
            },
        ),
        migrations.CreateModel(
            name='Modern5DeveloperSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=100, verbose_name='Skill Title')),
                ('skill_proficiency_percent', models.IntegerField(default=95, help_text='Enter value score from 1 to 100')),
                ('icon_choice', models.CharField(default='fab fa-python', help_text='FontAwesome icon class name string (e.g., fab fa-python, fab fa-docker, fa fa-database)', max_length=50)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_skills', to='modern5.modern5visualdeck')),
            ],
            options={
                'verbose_name': 'modern5 Developer Tech Badge',
                'verbose_name_plural': 'modern5 Developer Tech Badges',
            },
        ),
        migrations.CreateModel(
            name='Modern5ContractMailbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=120)),
                ('client_email', models.EmailField(max_length=254)),
                ('project_budget_estimate', models.CharField(default='₦500,000 - ₦1,000,000', help_text='e.g., ₦1,000,000+', max_length=100)),
                ('project_brief_body', models.TextField()),
                ('is_processed', models.BooleanField(default=False, verbose_name='Reviewed / Responded')),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_mailbox', to='modern5.modern5visualdeck')),
            ],
            options={
                'verbose_name': 'modern5 Contract Mailbox Message',
                'verbose_name_plural': 'modern5 Contract Mailbox Messages',
                'ordering': ['-received_at'],
            },
        ),
    ]
