# Generated by Django 6.1 on 2026-08-27 12:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('sort_order', models.IntegerField(default=0, help_text='Controls the left-to-right alignment order inside the navigation bar strip')),
            ],
            options={
                'verbose_name': 'Restaurant Category',
                'verbose_name_plural': 'Restaurant Categories',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FoodMenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, help_text='Brief ingredient overview or dish explanation')),
                ('price', models.DecimalField(decimal_places=2, help_text='Set price tag amount in Naira', max_digits=10)),
                ('image', models.ImageField(blank=True, help_text='Square aspect ratio food image asset', null=True, upload_to='menu_food_items/')),
                ('is_available', models.BooleanField(default=True, verbose_name='In Kitchen Stock')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='advance2.restaurantcategory')),
            ],
            options={
                'verbose_name': 'Food Menu Item',
                'verbose_name_plural': 'Food Menu Items',
            },
        ),
        migrations.CreateModel(
            name='RestaurantProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_name', models.CharField(max_length=120, unique=True)),
                ('restaurant_slug', models.SlugField(help_text='e.g., iya-meta-hq', max_length=120, unique=True)),
                ('restaurant_logo', models.ImageField(blank=True, help_text='Upload your official restaurant image icon asset', null=True, upload_to='restaurant_logos/')),
                ('restaurant_cover_photo', models.ImageField(blank=True, help_text='The square card display image shown next to restaurant meta details', null=True, upload_to='restaurant_covers/')),
                ('cuisine_type', models.CharField(default='African Restaurant', help_text='e.g., African Restaurant, Fast Food, Pastries', max_length=100)),
                ('delivery_time_range', models.CharField(default='15 - 30 mins', help_text='Estimated preparation and dispatch speed marker', max_length=40)),
                ('rating_display_text', models.CharField(default='4.5 (10k+ ratings)', help_text='e.g., 4.3 (13.1K+)', max_length=20)),
                ('operational_status_lbl', models.CharField(default='OPENS 10:00 AM', help_text='e.g., CLOSED • OPENS 10:00 AM', max_length=50)),
                ('footer_phone_line', models.CharField(default='+234', max_length=20)),
                ('footer_physical_address', models.CharField(default='Lagos, Nigeria', max_length=255)),
                ('is_restaurant_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Professional Restaurant Profile',
                'verbose_name_plural': 'Professional Restaurant Profiles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='restaurantcategory',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_categories', to='advance2.restaurantprofile'),
        ),
    ]
