# Generated by Django 6.1 on 2026-08-27 20:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advance2', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurantprofile',
            name='restaurant_name',
        ),
        migrations.RemoveField(
            model_name='restaurantprofile',
            name='restaurant_slug',
        ),
        migrations.RemoveField(
            model_name='restaurantprofile',
            name='user',
        ),
        migrations.CreateModel(
            name='Modern2SlugTenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_name', models.CharField(max_length=120, unique=True, verbose_name='Restaurant Name')),
                ('restaurant_slug', models.SlugField(help_text='e.g., foodco-hq', max_length=120, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User Account')),
            ],
            options={
                'verbose_name': 'Modern2 SaaS Tenant',
                'verbose_name_plural': 'Modern2 SaaS Tenants',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='restaurantprofile',
            name='restaurant_identity',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_profile', to='advance2.modern2slugtenant', verbose_name='SaaS Identity Link'),
            preserve_default=False,
        ),
    ]
