# Generated by Django 6.1 on 2026-08-27 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advance2', '0002_remove_restaurantprofile_restaurant_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantprofile',
            name='restaurant_identity',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_profile', to='advance2.modern2slugtenant', verbose_name='SaaS Identity Link'),
        ),
    ]
