# Generated by Django 6.1 on 2026-08-31 00:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advance2', '0003_alter_restaurantprofile_restaurant_identity'),
        ('super_admin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modern2slugtenant',
            name='assigned_agent',
            field=models.ForeignKey(blank=True, help_text='The field agent tracking this premium food user profile account registry', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modern2_onboarded_vendors', to='super_admin.agentprofile'),
        ),
    ]
