# Generated by Django 6.1 on 2026-10-02 09:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('super_admin', '0015_alter_domainengine_app_target'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='modern12SalonStoreFront',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_email', models.EmailField(default='info@prettyautos.ng', max_length=254, verbose_name='Official Support Email')),
                ('contact_phone', models.CharField(default='+234 (0) 803 456 7891', max_length=50, verbose_name='Contact Phone Line')),
                ('contact_address', models.CharField(default='203 Fake St. Lekki Phase 1, Lagos, Nigeria', max_length=255, verbose_name='Physical Depot Address')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='modern12_logos/', verbose_name='Salon Logo Graphic')),
                ('hero_title', models.CharField(default='Beauty Salon', max_length=150, verbose_name='Hero Title Main Headline')),
                ('hero_subtitle', models.CharField(default='Pretty Menu & Premium Grooming Services Tailored For You.', max_length=255, verbose_name='Hero Subtitle Copy Block')),
                ('hero_banner_image', models.ImageField(blank=True, null=True, upload_to='modern12_banners/', verbose_name='Hero Background Parallax Banner')),
                ('feature_1_title', models.CharField(default='Skin & Beauty Care', max_length=100, verbose_name='Feature 1 Card Title')),
                ('feature_1_desc', models.TextField(default='Premium facial micro-treatment layouts engineered to restore organic cellular glow safely.', verbose_name='Feature 1 Short Copy Text')),
                ('feature_2_title', models.CharField(default='Makeup Pro', max_length=100, verbose_name='Feature 2 Card Title')),
                ('feature_2_desc', models.TextField(default='Red-carpet cosmetic contours and flawless tone blends matched for high-end events.', verbose_name='Feature 2 Short Copy Text')),
                ('feature_3_title', models.CharField(default='Hair Styling', max_length=100, verbose_name='Feature 3 Card Title')),
                ('feature_3_desc', models.TextField(default='Precision texturing, custom weaving, and deep therapeutic scalp care routines.', verbose_name='Feature 3 Short Copy Text')),
                ('about_headline', models.CharField(default='Welcome to Pretty A Beauty Salon Website', max_length=200, verbose_name='About View Section Headline')),
                ('about_description_copy', models.TextField(default='Premium multi-tenant beauty grooming matrices, custom texturing hair hubs, and executive skin styling networks curated out of live inventory profiles to deliver absolute aesthetic luxury.', verbose_name='About Detailed Narrative Paragraph Copy')),
                ('about_banner_image', models.ImageField(blank=True, null=True, upload_to='modern12_about/', verbose_name='About Section Side Accent Graphic')),
                ('campaign_headline', models.CharField(default='Student Discount Strategy', max_length=150, verbose_name='Campaign Promotional Title')),
                ('campaign_description', models.TextField(default='Flash your active university identification credentials on terminal checkouts to claim 25% off all basic haircuts, therapeutic hair coloring, and skin cleansing matrix sessions.', verbose_name='Campaign Copy Statement Block')),
                ('stat_makeovers', models.CharField(default='1,500+', max_length=40, verbose_name='Stat Counter: Makeup Actions')),
                ('stat_procedures', models.CharField(default='2,840', max_length=40, verbose_name='Stat Counter: Procedures Met')),
                ('stat_clients', models.CharField(default='4,200+', max_length=40, verbose_name='Stat Counter: Glad Platform Clients')),
                ('stat_treatments', models.CharField(default='980', max_length=40, verbose_name='Stat Counter: Skin Treatment Logs')),
                ('facebook_url', models.URLField(blank=True, help_text='Optional profile link.', null=True, verbose_name='Merchant Facebook URL')),
                ('twitter_url', models.URLField(blank=True, help_text='Optional profile link.', null=True, verbose_name='Merchant Twitter / X URL')),
                ('instagram_url', models.URLField(blank=True, help_text='Optional profile link.', null=True, verbose_name='Merchant Instagram URL')),
                ('initialized_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'modern12 Salon Store Profile',
                'verbose_name_plural': 'modern12 Salon Store Profiles',
                'ordering': ['-initialized_at'],
            },
        ),
        migrations.CreateModel(
            name='modern12SalonService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_title', models.CharField(help_text='e.g. Bridal Glam Package', max_length=120, verbose_name='Grooming Package Title')),
                ('service_price', models.DecimalField(decimal_places=2, default=0.0, help_text='Total treatment fee in Naira', max_digits=12)),
                ('service_features_list', models.TextField(default='• Full Face Contouring\n• Premium Lash Extensions\n• Setting Spray Matte Fix\n• Professional Touch-up Kit Included', help_text='Insert features line items. Start each parameter line with a bullet point (•) or a clean hyphen (-).', verbose_name='Package Features Checklist Lines')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salon_services', to='modern12.modern12salonstorefront')),
            ],
            options={
                'verbose_name': 'modern12 Salon Pricing Tier Card',
                'verbose_name_plural': 'modern12 Salon Pricing Tier Cards',
            },
        ),
        migrations.CreateModel(
            name='modern12SalonProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(help_text='e.g. Matte Crimson Red Lipstick', max_length=150, verbose_name='Product Brand & Name')),
                ('product_category', models.CharField(choices=[('PERFUME', 'Exotic Perfumes / Scents'), ('HAIR', 'Premium Hair Bundles / Weaves'), ('LIPSTICK', 'Lipsticks / Lip Gloss'), ('EYELASH', 'Eyelashes / Eye Enhancements'), ('OTHER', 'General Cosmetics & Care')], default='OTHER', max_length=20, verbose_name='Product Category Group')),
                ('product_price', models.DecimalField(decimal_places=2, default=0.0, help_text='Retail selling fee in Naira', max_digits=12)),
                ('product_image', models.ImageField(help_text='Upload a crisp, high-resolution product picture', upload_to='modern12_shop/')),
                ('product_description', models.TextField(default='Premium salon-grade quality checked and approved.', verbose_name='Product Description / Details')),
                ('is_featured_on_home', models.BooleanField(default=False, help_text='Check this box to push this retail item directly to your index page view layout.', verbose_name='Showcase on Home Page Product Sliders')),
                ('is_in_stock', models.BooleanField(default=True, verbose_name='Item Is Available In Stock Grid')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salon_products', to='modern12.modern12salonstorefront')),
            ],
            options={
                'verbose_name': 'modern12 Salon Shop Product',
                'verbose_name_plural': 'modern12 Salon Shop Products',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='modern12SalonBlogArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_title', models.CharField(max_length=250, verbose_name='Article Title')),
                ('author_display_name', models.CharField(default='Lounge Director', max_length=100)),
                ('article_thumbnail', models.ImageField(upload_to='modern12_blogs/')),
                ('article_summary', models.TextField(default='Premium skin maintenance guide review overview.')),
                ('article_body_content', models.TextField(default='Full journalism entry logs specifications.')),
                ('published_date', models.DateField(auto_now_add=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salon_articles', to='modern12.modern12salonstorefront')),
            ],
            options={
                'verbose_name': 'modern12 Salon Blog Post',
                'verbose_name_plural': 'modern12 Salon Blog Posts',
                'ordering': ['-published_date'],
            },
        ),
        migrations.CreateModel(
            name='modern12PortfolioWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_title', models.CharField(help_text='e.g. Matte Lips Makeover', max_length=150, verbose_name='Transformation Title')),
                ('work_category', models.CharField(choices=[('MAKEUP', 'Cosmetics / Make Up'), ('FACIAL', 'Facial & Spa Treatment'), ('HAIR', 'Hair Cut / Styling'), ('NAIL', 'Nail Art / Pedicure')], default='HAIR', max_length=20, verbose_name='Lookbook Category')),
                ('work_image', models.ImageField(help_text='Upload crisp transformation portfolio look', upload_to='modern12_lookbooks/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_works', to='modern12.modern12salonstorefront')),
            ],
            options={
                'verbose_name': 'modern12 Portfolio Lookbook Image',
                'verbose_name_plural': 'modern12 Portfolio Lookbook Images',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='modern12SalonStylist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stylist_name', models.CharField(max_length=120, verbose_name='Expert Full Name')),
                ('stylist_role', models.CharField(help_text='e.g. Master Barber, Cosmetic Lead, Nail Tech Consultant', max_length=120, verbose_name='Corporate Designation')),
                ('stylist_avatar', models.ImageField(upload_to='modern12_stylists/', verbose_name='Profile Picture')),
                ('stylist_bio_summary', models.TextField(default='Vetted industry specialist.', verbose_name='Short Professional Bio')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salon_stylists', to='modern12.modern12salonstorefront')),
            ],
            options={
                'verbose_name': 'modern12 Salon Expert Stylist Card',
                'verbose_name_plural': 'modern12 Salon Expert Stylist Cards',
            },
        ),
        migrations.CreateModel(
            name='modern12SalonTenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=120, unique=True, verbose_name='Salon Business Name')),
                ('slug_name', models.SlugField(help_text='e.g., corex-salon, elite-makeovers', max_length=120, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_agent', models.ForeignKey(blank=True, help_text='The field agent tracking this premium beauty salon profile registry', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modern12_onboarded_salons', to='super_admin.agentprofile', verbose_name='Assigned Agent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User Account')),
            ],
            options={
                'verbose_name': 'modern12 Salon Tenant',
                'verbose_name_plural': 'modern12 Salon Tenants',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='modern12salonstorefront',
            name='tenant_identity',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='studio_profile', to='modern12.modern12salontenant', verbose_name='SaaS Identity Link'),
        ),
    ]
