# Generated by Django 6.1 on 2026-10-02 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modern12', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modern12salonstorefront',
            name='hours_banner_image',
            field=models.ImageField(blank=True, help_text='Upload a picture of professional barbering equipment to show on the left side panel.', null=True, upload_to='modern12_hours/', verbose_name='Working Hours Left Side Image Display Banner'),
        ),
        migrations.AddField(
            model_name='modern12salonstorefront',
            name='hours_friday',
            field=models.CharField(default='09 AM - 09 PM', max_length=50, verbose_name='Friday Operational Timing'),
        ),
        migrations.AddField(
            model_name='modern12salonstorefront',
            name='hours_monday',
            field=models.CharField(default='09 AM - 09 PM', max_length=50, verbose_name='Monday Operational Timing'),
        ),
        migrations.AddField(
            model_name='modern12salonstorefront',
            name='hours_thursday',
            field=models.CharField(default='09 AM - 09 PM', max_length=50, verbose_name='Thursday Operational Timing'),
        ),
        migrations.AddField(
            model_name='modern12salonstorefront',
            name='hours_tuesday',
            field=models.CharField(default='09 AM - 09 PM', max_length=50, verbose_name='Tuesday Operational Timing'),
        ),
        migrations.AddField(
            model_name='modern12salonstorefront',
            name='hours_wednesday',
            field=models.CharField(default='09 AM - 09 PM', max_length=50, verbose_name='Wednesday Operational Timing'),
        ),
        migrations.AddField(
            model_name='modern12salonstorefront',
            name='hours_weekend',
            field=models.CharField(default='Closed', max_length=50, verbose_name='Weekend Operational Timing (Sat / Sun)'),
        ),
    ]
