# Generated by Django 6.1 on 2026-10-02 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modern12', '0002_modern12salonstorefront_hours_banner_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modern12salonproduct',
            name='product_category',
            field=models.CharField(choices=[('PERFUME', 'Exotic Perfumes / Scents'), ('OTHER', 'General Cosmetics & Care')], default='OTHER', max_length=20, verbose_name='Product Category Group'),
        ),
        migrations.AlterField(
            model_name='modern12salonproduct',
            name='product_name',
            field=models.CharField(help_text='e.g. Royal Oud Perfume, Texture Wax', max_length=150, verbose_name='Product Brand & Name'),
        ),
    ]
