# Generated by Django 6.1 on 2026-10-02 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modern12', '0003_alter_modern12salonproduct_product_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modern12salonstorefront',
            name='hours_saturday',
            field=models.CharField(default='09 AM - 06 PM', max_length=50, verbose_name='Saturday Operational Timing'),
        ),
        migrations.AlterField(
            model_name='modern12salonstorefront',
            name='hours_weekend',
            field=models.CharField(default='Closed', max_length=50, verbose_name='Sunday Operational Timing'),
        ),
    ]
