# Generated by Django 6.1 on 2026-08-23 18:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, help_text='Upload a banner photo from your computer', null=True, upload_to='categories/')),
                ('order', models.IntegerField(default=0)),
                ('whatsapp_number', models.CharField(default='2349020425819', help_text='Enter number with country code, no symbols (e.g., 2349020425819)', max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(blank=True, help_text='Upload a dish photo from your computer', null=True, upload_to='food_items/')),
                ('is_available', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='menu.category')),
            ],
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(help_text='Official name of the restaurant lounge', max_length=100, unique=True)),
                ('slug', models.SlugField(help_text="The dynamic web link name extension (e.g., 'the-victuals' for food_://menu.com)", max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck this to instantly block access to their menu if they fail to pay their ₦10k subscription')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(help_text='The private login manager account for this restaurant', on_delete=django.db.models.deletion.CASCADE, related_name='tenant_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'SaaS Client Tenant',
                'verbose_name_plural': 'SaaS Client Tenants',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RestaurantProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_name', models.CharField(default='The Victuals', max_length=100)),
                ('logo', models.ImageField(blank=True, help_text='Upload your venue logo', null=True, upload_to='branding/')),
                ('phone_number', models.CharField(default='2349020425819', help_text='For dialing buttons', max_length=20)),
                ('whatsapp_number', models.CharField(default='2349020425819', help_text='For sending order baskets', max_length=20)),
                ('primary_color', models.CharField(default='#dc2626', help_text='Hex color code for pills/buttons (e.g., #dc2626)', max_length=10)),
                ('outer_bg_color', models.CharField(default='#0c0c0d', help_text='Backdrop margins tone color (e.g., #0c0c0d)', max_length=10)),
                ('inner_bg_color', models.CharField(default='#121212', help_text='Inner canvas main background (e.g., #121212)', max_length=10)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='menu.tenant')),
            ],
            options={
                'verbose_name_plural': 'Restaurant Configuration Profiles',
            },
        ),
        migrations.CreateModel(
            name='CustomerFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_number', models.CharField(blank=True, help_text='Optional diner table location', max_length=10, null=True)),
                ('rating', models.IntegerField(choices=[(1, '1 Stars'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')], default=5)),
                ('comment', models.TextField(help_text='The core food/experience review text')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='menu.tenant')),
            ],
            options={
                'verbose_name_plural': 'Customer Feedback Entries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='category',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='menu.tenant'),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('tenant', 'name')},
        ),
    ]
