# Generated by Django 6.1 on 2026-08-23 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantprofile',
            name='address',
            field=models.CharField(default='Somolu, Lagos Mainland', help_text='Physical restaurant location address string', max_length=255),
        ),
    ]
