# Generated by Django 6.1 on 2026-08-24 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_restaurantprofile_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_phone', models.CharField(default='2349020425819', help_text='Your developer calling line', max_length=20)),
                ('admin_whatsapp', models.CharField(default='2349020425819', help_text='Your developer destination order link line', max_length=20)),
                ('mock_rented_shops_base', models.IntegerField(default=14, help_text='Base number of shops rented to display on marketing layouts (Editable)')),
            ],
            options={
                'verbose_name': 'Master SaaS Platform Setting',
                'verbose_name_plural': 'Master SaaS Platform Settings',
            },
        ),
    ]
