# Generated by Django 6.1 on 2026-08-24 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_platformsetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='business_type',
            field=models.CharField(choices=[('RESTAURANT', 'Restaurant / Lounge / Bar'), ('FASHION', 'Fashion Boutique / Apparel / Store')], default='RESTAURANT', help_text='Choose between a single-column food menu or a 3-column fashion lookbook grid', max_length=20),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='slug',
            field=models.SlugField(help_text="The dynamic web link name extension (e.g., 'the-victuals')", max_length=100, unique=True),
        ),
    ]
