# Generated by Django 6.1 on 2026-08-24 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_tenant_business_type_alter_tenant_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformsetting',
            name='left_banner_image',
            field=models.ImageField(blank=True, help_text='Animated graphic or screenshot for the LEFT side of the landing page', null=True, upload_to='marketing/'),
        ),
        migrations.AddField(
            model_name='platformsetting',
            name='right_banner_image',
            field=models.ImageField(blank=True, help_text='Animated graphic or screenshot for the RIGHT side of the landing page', null=True, upload_to='marketing/'),
        ),
    ]
