# Generated by Django 6.1 on 2026-08-24 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_platformsetting_left_banner_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformsetting',
            name='landing_background_image',
            field=models.ImageField(blank=True, help_text='Full-screen ambient background graphic asset for the landing page', null=True, upload_to='marketing/'),
        ),
    ]
