# Generated by Django 6.1 on 2026-08-25 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_platformsetting_landing_background_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShowcaseTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label_name', models.CharField(help_text='e.g., DINER MENU, BOUTIQUE, COCKTAILS', max_length=30)),
                ('showcase_image', models.ImageField(help_text='Upload the main screenshot mockup for this industry category', upload_to='templates_gallery/')),
            ],
            options={
                'verbose_name': 'Showcase Template Card',
                'verbose_name_plural': 'Showcase Template Cards',
            },
        ),
    ]
