# Generated by Django 6.1 on 2026-08-25 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_showcasetemplate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fooditem',
            options={'ordering': ['category', 'name'], 'verbose_name': 'Catalog Item', 'verbose_name_plural': 'Items Catalog'},
        ),
    ]
