# Generated by Django 6.1 on 2026-08-25 04:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0008_alter_fooditem_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='payment_status',
            field=models.CharField(choices=[('UNPAID', '🔴 Unpaid (Expired)'), ('PAID', '🟢 Paid (Active)')], default='UNPAID', help_text='Blinker indicator status row', max_length=10),
        ),
        migrations.AddField(
            model_name='tenant',
            name='virtual_account_number',
            field=models.CharField(blank=True, default='9920384192', help_text='Unique Providus/Sterling Bank virtual collection card tracking row', max_length=20),
        ),
        migrations.AddField(
            model_name='tenant',
            name='virtual_bank_name',
            field=models.CharField(default='Monnify / Sterling Bank', help_text='Assigned platform bank settlement name', max_length=30),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='business_name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='business_type',
            field=models.CharField(choices=[('RESTAURANT', 'Restaurant / Lounge / Bar'), ('FASHION', 'Fashion Boutique / Apparel / Store')], default='RESTAURANT', max_length=20),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='AgentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_code', models.CharField(help_text='Unique Identification Code (e.g., ABUJA01, ENUGU05)', max_length=15, unique=True)),
                ('assigned_state', models.CharField(help_text='Primary deployment operational zone', max_length=40)),
                ('phone_number', models.CharField(max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agent_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Field Agent Profile',
                'verbose_name_plural': 'Field Agent Profiles',
            },
        ),
        migrations.AddField(
            model_name='tenant',
            name='assigned_agent',
            field=models.ForeignKey(blank=True, help_text='The field agent tracking this user account', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='onboarded_vendors', to='menu.agentprofile'),
        ),
    ]
