# Generated by Django 6.1 on 2026-08-25 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0009_tenant_payment_status_tenant_virtual_account_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBillingNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(default='Access Bank / Wema Bank', help_text='Your master corporate receiving bank name', max_length=50)),
                ('account_number', models.CharField(default='0123456789', help_text='Your main corporate account numbers line', max_length=15)),
                ('account_name', models.CharField(default='The Victuals SaaS Limited', help_text='Your corporate bank account name', max_length=100)),
                ('subscription_amount', models.DecimalField(decimal_places=2, default=10000.0, max_digits=10)),
                ('payment_instructions', models.TextField(default='Kindly make a direct bank transfer or USSD payment to our corporate account above to activate/renew your lookup catalog instantly. Send payment proof to the lead admin.')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='billing_notice', to='menu.tenant')),
            ],
            options={
                'verbose_name': 'Merchant Billing Detail',
                'verbose_name_plural': 'Merchant Billing Details',
            },
        ),
    ]
