# Generated by Django 6.1 on 2026-08-25 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0010_userbillingnotice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='business_type',
            field=models.CharField(choices=[('RESTAURANT', 'Restaurant / Lounge / Bar'), ('FASHION', 'Fashion Boutique / Apparel / Store'), ('GROCERY', 'Supermarket, Grocery & Pharmacy Operations')], default='RESTAURANT', max_length=20),
        ),
    ]
