# Generated by Django 6.1 on 2026-08-27 15:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0011_alter_tenant_business_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userbillingnotice',
            options={'verbose_name': 'User Billing Notice', 'verbose_name_plural': 'User Billing Notices'},
        ),
        migrations.RemoveField(
            model_name='userbillingnotice',
            name='tenant',
        ),
        migrations.AddField(
            model_name='userbillingnotice',
            name='merchant_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='billing_notices', to=settings.AUTH_USER_MODEL, verbose_name='Merchant Admin User'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userbillingnotice',
            name='account_name',
            field=models.CharField(help_text='Your corporate bank account name', max_length=150),
        ),
        migrations.AlterField(
            model_name='userbillingnotice',
            name='account_number',
            field=models.CharField(help_text='Your main corporate account numbers line', max_length=20),
        ),
        migrations.AlterField(
            model_name='userbillingnotice',
            name='bank_name',
            field=models.CharField(help_text='Your master corporate receiving bank name', max_length=100),
        ),
        migrations.AlterField(
            model_name='userbillingnotice',
            name='payment_instructions',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='userbillingnotice',
            name='subscription_amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
