# Generated by Django 6.1 on 2026-08-29 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0012_alter_userbillingnotice_options_and_more'),
        ('super_admin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agentprofile',
            name='user',
        ),
        migrations.AlterField(
            model_name='tenant',
            name='assigned_agent',
            field=models.ForeignKey(blank=True, help_text='The field agent tracking this user account', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='onboarded_vendors', to='super_admin.agentprofile'),
        ),
        migrations.DeleteModel(
            name='PlatformSetting',
        ),
        migrations.DeleteModel(
            name='ShowcaseTemplate',
        ),
        migrations.RemoveField(
            model_name='userbillingnotice',
            name='merchant_user',
        ),
        migrations.AlterField(
            model_name='category',
            name='whatsapp_number',
            field=models.CharField(default='2349020425819', help_text='Enter number with country code, no symbols', max_length=20),
        ),
        migrations.AlterField(
            model_name='restaurantprofile',
            name='inner_bg_color',
            field=models.CharField(default='#121212', help_text='Inner canvas main background', max_length=10),
        ),
        migrations.AlterField(
            model_name='restaurantprofile',
            name='outer_bg_color',
            field=models.CharField(default='#0c0c0d', help_text='Backdrop margins tone color', max_length=10),
        ),
        migrations.AlterField(
            model_name='restaurantprofile',
            name='primary_color',
            field=models.CharField(default='#dc2626', help_text='Hex color code for pills/buttons', max_length=10),
        ),
        migrations.DeleteModel(
            name='AgentProfile',
        ),
        migrations.DeleteModel(
            name='UserBillingNotice',
        ),
    ]
