# Generated by Django 6.1 on 2026-08-31 08:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('super_admin', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Modern3SlugTenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_name', models.CharField(max_length=120, unique=True, verbose_name='Hospital Name')),
                ('hospital_slug', models.SlugField(help_text='e.g., medilab-lekki-hq', max_length=120, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_agent', models.ForeignKey(blank=True, help_text='The field agent tracking this premium hospital profile registry', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modern3_onboarded_hospitals', to='super_admin.agentprofile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User Account')),
            ],
            options={
                'verbose_name': 'Modern3 SaaS Tenant',
                'verbose_name_plural': 'Modern3 SaaS Tenants',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Modern3StoreFront',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_email', models.EmailField(default='contact@example.com', max_length=254)),
                ('emergency_phone_line', models.CharField(default='+1 5589 55488 55', max_length=30)),
                ('hero_title', models.CharField(default='WELCOME TO MEDILAB', max_length=150)),
                ('hero_sub_headline', models.TextField(default='Providing world-class comprehensive medical care configurations.')),
                ('why_choose_us_headline', models.CharField(default='Why Choose Medilab?', max_length=200)),
                ('why_choose_us_body_text', models.TextField(default='Brief summary detailing medical care excellence parameters.')),
                ('value_card_one_title', models.CharField(default='Corporis voluptates', max_length=100)),
                ('value_card_one_body', models.TextField(default='Ullamco laboris nisi ut aliquip ex ea commodo consequat.')),
                ('value_card_two_title', models.CharField(default='Ullamco laboris', max_length=100)),
                ('value_card_two_body', models.TextField(default='Ullamco laboris nisi ut aliquip ex ea commodo consequat.')),
                ('value_card_three_title', models.CharField(default='Labore consequatur', max_length=100)),
                ('value_card_three_body', models.TextField(default='Ullamco laboris nisi ut aliquip ex ea commodo consequat.')),
                ('about_main_description', models.TextField(default='Detailed healthcare facility history or manifesto block.')),
                ('about_video_url', models.URLField(default='https://youtube.com', help_text='Hospital video tour clip link')),
                ('about_showcase_image', models.ImageField(blank=True, null=True, upload_to='hospital_about/')),
                ('count_doctors', models.IntegerField(default=85)),
                ('count_departments', models.IntegerField(default=18)),
                ('count_research_labs', models.IntegerField(default=12)),
                ('count_awards', models.IntegerField(default=150)),
                ('contact_headline', models.CharField(default='Contact', max_length=150)),
                ('contact_description', models.TextField(default='Necessitatibus eius consequatur ex aliquid fuga eum quidem sint.')),
                ('google_maps_embed_url', models.TextField(default='https://google.com...', help_text='Paste raw Google Maps iframe source URL link string')),
                ('hospital_physical_address', models.CharField(default='A108 Adam Street, New York, NY 535022', max_length=255)),
                ('initialized_at', models.DateTimeField(auto_now_add=True)),
                ('tenant_identity', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hospital_profile', to='modern3.modern3slugtenant', verbose_name='SaaS Identity Link')),
            ],
            options={
                'verbose_name': 'Hospital Store Profile',
                'verbose_name_plural': 'Hospital Store Profiles',
                'ordering': ['-initialized_at'],
            },
        ),
        migrations.CreateModel(
            name='MedicalDoctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_name', models.CharField(max_length=120)),
                ('medical_title', models.CharField(help_text='e.g., Chief Medical Officer, Anesthesiologist', max_length=100)),
                ('doctor_biography', models.TextField(blank=True, help_text='Brief summary paragraph statement')),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='hospital_doctors/')),
                ('twitter_link', models.URLField(blank=True, default='https://twitter.com', null=True)),
                ('facebook_link', models.URLField(blank=True, default='https://facebook.com', null=True)),
                ('instagram_link', models.URLField(blank=True, default='https://instagram.com', null=True)),
                ('linkedin_link', models.URLField(blank=True, default='https://linkedin.com', null=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hospital_doctors', to='modern3.modern3storefront')),
            ],
            options={
                'verbose_name': 'Medical Team Doctor',
                'verbose_name_plural': 'Medical Team Doctors',
            },
        ),
        migrations.CreateModel(
            name='MedicalAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=120)),
                ('patient_email', models.EmailField(max_length=254)),
                ('patient_phone', models.CharField(max_length=30)),
                ('appointment_date', models.CharField(help_text='Date or text string from the calendar picker template link', max_length=100)),
                ('selected_department', models.CharField(max_length=120)),
                ('selected_doctor', models.CharField(max_length=120)),
                ('patient_message', models.TextField(blank=True)),
                ('is_reviewed', models.BooleanField(default=False, verbose_name='Processed / Approved')),
                ('logged_at', models.DateTimeField(auto_now_add=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hospital_appointments', to='modern3.modern3storefront')),
            ],
            options={
                'verbose_name': 'Incoming Patient Appointment',
                'verbose_name_plural': 'Incoming Patient Appointments',
                'ordering': ['-logged_at'],
            },
        ),
        migrations.CreateModel(
            name='HospitalTestimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=120)),
                ('patient_title_or_role', models.CharField(default='Patient', help_text='e.g., Recovered Patient, Local Client', max_length=100)),
                ('rating_stars', models.IntegerField(default=5, help_text='Enter number score from 1 to 5')),
                ('review_text', models.TextField()),
                ('patient_avatar', models.ImageField(blank=True, null=True, upload_to='hospital_reviews/')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hospital_testimonials', to='modern3.modern3storefront')),
            ],
            options={
                'verbose_name': 'Patient Testimonial Story',
                'verbose_name_plural': 'Patient Testimonial Stories',
            },
        ),
        migrations.CreateModel(
            name='HospitalService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=120, verbose_name='Service Title')),
                ('service_description', models.TextField(verbose_name='Service Summary Paragraph')),
                ('icon_choice', models.CharField(default='bi-heart-pulse', help_text='Bootstrap icon class name string (e.g., bi-heart-pulse, bi-pills, bi-stethoscope)', max_length=50)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hospital_services', to='modern3.modern3storefront')),
            ],
            options={
                'verbose_name': 'Hospital Service Offer',
                'verbose_name_plural': 'Hospital Service Offers',
            },
        ),
        migrations.CreateModel(
            name='HospitalGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gallery_photo', models.ImageField(upload_to='hospital_gallery/')),
                ('image_caption', models.CharField(blank=True, help_text='Short title popup name label', max_length=150, null=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hospital_gallery', to='modern3.modern3storefront')),
            ],
            options={
                'verbose_name': 'Hospital Gallery Image',
                'verbose_name_plural': 'Hospital Gallery Images',
            },
        ),
        migrations.CreateModel(
            name='HospitalFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=255)),
                ('answer_text', models.TextField()),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hospital_faqs', to='modern3.modern3storefront')),
            ],
            options={
                'verbose_name': 'Hospital FAQ Drawer',
                'verbose_name_plural': 'Hospital FAQ Drawers',
            },
        ),
        migrations.CreateModel(
            name='HospitalDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tab Menu Title')),
                ('headline', models.CharField(max_length=180, verbose_name='Content Primary Header Row')),
                ('description', models.TextField(verbose_name='Detailed Summary Context Text')),
                ('showcase_photo', models.ImageField(blank=True, null=True, upload_to='hospital_departments/')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hospital_departments', to='modern3.modern3storefront')),
            ],
            options={
                'verbose_name': 'Hospital Department Tab',
                'verbose_name_plural': 'Hospital Department Tabs',
            },
        ),
        migrations.CreateModel(
            name='HospitalContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name', models.CharField(max_length=120)),
                ('sender_email', models.EmailField(max_length=254)),
                ('message_subject', models.CharField(max_length=200)),
                ('message_body', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hospital_mailbox', to='modern3.modern3storefront')),
            ],
            options={
                'verbose_name': 'Mailbox Feedback Message',
                'verbose_name_plural': 'Mailbox Feedback Messages',
                'ordering': ['-received_at'],
            },
        ),
    ]
