# Generated by Django 6.1 on 2026-08-31 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modern3', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modern3storefront',
            name='hospital_logo',
            field=models.ImageField(blank=True, help_text='Upload a square aspect ratio branding logo icon to display next to the site name header text row', null=True, upload_to='hospital_logos/'),
        ),
    ]
