# Generated by Django 6.1 on 2026-09-01 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modern3', '0002_modern3storefront_hospital_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='modern3storefront',
            name='hero_background_image',
            field=models.ImageField(blank=True, help_text='Upload a high-resolution ambient background graphic picture for your main landing section', null=True, upload_to='hospital_hero_bg/'),
        ),
    ]
