# Generated by Django 6.1 on 2026-09-10 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modern3', '0003_modern3storefront_hero_background_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modern3slugtenant',
            name='hospital_slug',
            field=models.SlugField(help_text='e.g., hospital', max_length=120, unique=True),
        ),
    ]
