# Generated by Django 6.1 on 2026-08-29 17:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_phone', models.CharField(default='2349020425819', help_text='Your developer calling line', max_length=20)),
                ('admin_whatsapp', models.CharField(default='2349020425819', help_text='Your developer destination order link line', max_length=20)),
                ('mock_rented_shops_base', models.IntegerField(default=14, help_text='Base number of shops rented to display on marketing layouts (Editable)')),
                ('left_banner_image', models.ImageField(blank=True, help_text='Animated graphic or screenshot for the LEFT side', null=True, upload_to='marketing/')),
                ('right_banner_image', models.ImageField(blank=True, help_text='Animated graphic or screenshot for the RIGHT side', null=True, upload_to='marketing/')),
                ('landing_background_image', models.ImageField(blank=True, help_text='Full-screen ambient background graphic asset', null=True, upload_to='marketing/')),
            ],
            options={
                'verbose_name': 'Master SaaS Platform Setting',
                'verbose_name_plural': 'Master SaaS Platform Settings',
            },
        ),
        migrations.CreateModel(
            name='ShowcaseTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label_name', models.CharField(help_text='e.g., DINER MENU, BOUTIQUE, COCKTAILS', max_length=30)),
                ('showcase_image', models.ImageField(help_text='Upload the main screenshot mockup', upload_to='templates_gallery/')),
            ],
            options={
                'verbose_name': 'Showcase Template Card',
                'verbose_name_plural': 'Showcase Template Cards',
            },
        ),
        migrations.CreateModel(
            name='AgentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_code', models.CharField(help_text='Unique Identification Code (e.g., ABUJA01, ENUGU05)', max_length=15, unique=True)),
                ('assigned_state', models.CharField(help_text='Primary deployment operational zone', max_length=40)),
                ('phone_number', models.CharField(max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agent_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Field Agent Profile',
                'verbose_name_plural': 'Field Agent Profiles',
            },
        ),
        migrations.CreateModel(
            name='UserBillingNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(help_text='Your master corporate receiving bank name', max_length=100)),
                ('account_number', models.CharField(help_text='Your main corporate account numbers line', max_length=20)),
                ('account_name', models.CharField(help_text='Your corporate bank account name', max_length=150)),
                ('subscription_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_instructions', models.TextField(blank=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('merchant_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='super_billing_notices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Billing Notice',
                'verbose_name_plural': 'User Billing Notices',
            },
        ),
    ]
