# Generated by Django 6.1 on 2026-08-31 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super_admin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='platformsetting',
            name='landing_background_image',
        ),
        migrations.RemoveField(
            model_name='platformsetting',
            name='left_banner_image',
        ),
        migrations.RemoveField(
            model_name='platformsetting',
            name='right_banner_image',
        ),
        migrations.AddField(
            model_name='platformsetting',
            name='server_state_amber',
            field=models.ImageField(blank=True, help_text='🔥 STATE 5: Thermal Overclock Image (e.g., Cyberpunk Amber Orange)', null=True, upload_to='server_states/'),
        ),
        migrations.AddField(
            model_name='platformsetting',
            name='server_state_blue',
            field=models.ImageField(blank=True, help_text='⚡ STATE 2: Shield Intercept Image (e.g., Tactical Cobalt Blue)', null=True, upload_to='server_states/'),
        ),
        migrations.AddField(
            model_name='platformsetting',
            name='server_state_default',
            field=models.ImageField(blank=True, help_text='🛡️ STATE 1: Base Default Server Console Image (e.g., Matrix Green)', null=True, upload_to='server_states/'),
        ),
        migrations.AddField(
            model_name='platformsetting',
            name='server_state_emerald',
            field=models.ImageField(blank=True, help_text='💎 STATE 4: System Locked Image (e.g., Emerald Guard Green)', null=True, upload_to='server_states/'),
        ),
        migrations.AddField(
            model_name='platformsetting',
            name='server_state_purple',
            field=models.ImageField(blank=True, help_text='🔮 STATE 3: Core Overload Image (e.g., Deep Citadel Purple)', null=True, upload_to='server_states/'),
        ),
    ]
