# Generated by Django 6.1 on 2026-09-01 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super_admin', '0002_remove_platformsetting_landing_background_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='showcasetemplate',
            name='screenshot_five',
            field=models.ImageField(blank=True, help_text='Optional: Fifth template layout view', null=True, upload_to='templates_gallery/'),
        ),
        migrations.AddField(
            model_name='showcasetemplate',
            name='screenshot_four',
            field=models.ImageField(blank=True, help_text='Optional: Fourth template layout view', null=True, upload_to='templates_gallery/'),
        ),
        migrations.AddField(
            model_name='showcasetemplate',
            name='screenshot_three',
            field=models.ImageField(blank=True, help_text='Optional: Third template layout view', null=True, upload_to='templates_gallery/'),
        ),
        migrations.AddField(
            model_name='showcasetemplate',
            name='screenshot_two',
            field=models.ImageField(blank=True, help_text='Optional: Second template layout view', null=True, upload_to='templates_gallery/'),
        ),
        migrations.AlterField(
            model_name='showcasetemplate',
            name='showcase_image',
            field=models.ImageField(help_text='Upload the primary thumbnail mockup screenshot', upload_to='templates_gallery/'),
        ),
    ]
