# Generated by Django 6.1 on 2026-09-01 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super_admin', '0003_showcasetemplate_screenshot_five_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='showcasetemplate',
            name='screenshot_five',
        ),
        migrations.RemoveField(
            model_name='showcasetemplate',
            name='screenshot_four',
        ),
        migrations.RemoveField(
            model_name='showcasetemplate',
            name='screenshot_three',
        ),
        migrations.RemoveField(
            model_name='showcasetemplate',
            name='screenshot_two',
        ),
        migrations.AddField(
            model_name='showcasetemplate',
            name='live_site_url',
            field=models.URLField(blank=True, help_text='Paste the live preview link (e.g., http://127.0.0)', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='showcasetemplate',
            name='label_name',
            field=models.CharField(help_text='e.g., DINER MENU, BELLMED CLINIC', max_length=30),
        ),
        migrations.AlterField(
            model_name='showcasetemplate',
            name='showcase_image',
            field=models.ImageField(help_text='Upload the main screenshot mockup', upload_to='templates_gallery/'),
        ),
    ]
