# Generated by Django 6.1 on 2026-09-01 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super_admin', '0004_remove_showcasetemplate_screenshot_five_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformsetting',
            name='about_text',
            field=models.TextField(default='This platform functions as a robust multi-tenant enterprise orchestration dashboard designed to provision data-isolated clinical and business store fronts natively.', help_text='Brief corporate developer synopsis, mission statement, or platform specifications description text.'),
        ),
        migrations.AddField(
            model_name='platformsetting',
            name='security_text',
            field=models.TextField(default='🔒 FIREWALL GATEWAY: Real-time traffic monitoring filtering matrix entries.\n🔒 AGENT ISOLATION: Strict cryptographic boundaries protecting merchant datasets.', help_text='Infrastructure security guidelines, firewall policies, or network certifications text configuration.'),
        ),
        migrations.AddField(
            model_name='platformsetting',
            name='services_text',
            field=models.TextField(default='▪️ CORE ENGINE ONBOARDING: Fast automation scripts for store creation.\n▪️ COMPREHENSIVE MEDICAL SUITE: Dynamic scheduling, specialist rosters, and intake management.', help_text='Line-separated text list of platform operational services for the header nav dropdown drawer panel.'),
        ),
    ]
