# Generated by Django 6.1 on 2026-09-01 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super_admin', '0005_platformsetting_about_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfrastructureMailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name', models.CharField(max_length=100)),
                ('sender_email', models.EmailField(max_length=254)),
                ('message_body', models.TextField()),
                ('logged_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Core Infrastructure Mail',
                'verbose_name_plural': 'Core Infrastructure Mails',
                'ordering': ['-logged_at'],
            },
        ),
    ]
