# Generated by Django 6.1 on 2026-09-03 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super_admin', '0006_infrastructuremaillog'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformsetting',
            name='platform_logo',
            field=models.ImageField(blank=True, help_text='Upload a premium translucent PNG logo to display beside Corex Server.', null=True, upload_to='platform_branding/'),
        ),
    ]
