# Generated by Django 6.1 on 2026-09-05 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super_admin', '0007_platformsetting_platform_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformsetting',
            name='server_state_eight',
            field=models.ImageField(blank=True, help_text='🛡️ STATE 8: Perimeter Firewall Security Image Shard', null=True, upload_to='server_states/'),
        ),
        migrations.AddField(
            model_name='platformsetting',
            name='server_state_nine',
            field=models.ImageField(blank=True, help_text='⚡ STATE 9: Quantum Network Grid Image Shard', null=True, upload_to='server_states/'),
        ),
        migrations.AddField(
            model_name='platformsetting',
            name='server_state_seven',
            field=models.ImageField(blank=True, help_text='🌌 STATE 7: Deep Cosmic Eclipse Image Shard', null=True, upload_to='server_states/'),
        ),
        migrations.AddField(
            model_name='platformsetting',
            name='server_state_six',
            field=models.ImageField(blank=True, help_text='📡 STATE 6: Core Matrix Extension Image Shard', null=True, upload_to='server_states/'),
        ),
        migrations.AddField(
            model_name='platformsetting',
            name='server_state_ten',
            field=models.ImageField(blank=True, help_text='💎 STATE 10: Supreme Enterprise Protocol Image Shard', null=True, upload_to='server_states/'),
        ),
    ]
