# Generated by Django 6.1 on 2026-09-10 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super_admin', '0008_platformsetting_server_state_eight_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DomainEngine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug_name', models.CharField(help_text='The lowercase subdomain text (e.g., foodco, bellmed)', max_length=100, unique=True)),
                ('app_target', models.CharField(choices=[('store', '🍉 LIST_STORE (Menu App)'), ('modern', '💪 LIST_MODERN (Gym App)'), ('modern2', '🍔 LIST_MODERN2 (Restaurant App)'), ('modern3', '🏥 LIST_MODERN3 (Hospital App)'), ('modern4', '❤️ LIST_MODERN4 (LoveCare App)'), ('modern5', '🎨 LIST_MODERN5 (Portfolio App)'), ('modern6', '🏡 LIST_MODERN6 (Homeland App)'), ('modern7', '🎓 LIST_MODERN7 (School App)')], default='modern5', help_text='Choose which list routing engine this belongs to', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Domain Engine Router',
                'verbose_name_plural': 'Domain Engine Routers',
            },
        ),
    ]
