# Generated by Django 6.1 on 2026-09-21 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super_admin', '0010_alter_domainengine_app_target'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domainengine',
            name='app_target',
            field=models.CharField(choices=[('store', '🍉 LIST_STORE (Menu App)'), ('modern', '💪 LIST_MODERN (Gym App)'), ('modern2', '🍔 LIST_MODERN2 (Restaurant App)'), ('modern3', '🏥 LIST_MODERN3 (Hospital App)'), ('modern4', '❤️ LIST_MODERN4 (LoveCare App)'), ('modern5', '🎨 LIST_MODERN5 (Portfolio App)'), ('modern6', '🏡 LIST_MODERN6 (Homeland App)'), ('modern7', '🎓 LIST_MODERN7 (School App)'), ('modern8', ' 🏡 LIST_MODERN8 (Funiture App'), ('modern9', ' 🏡 LIST_MODERN9 (fashion App')], default='modern5', help_text='Choose which list routing engine this belongs to', max_length=20),
        ),
    ]
