# Generated by Django 6.1 on 2026-09-14 16:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Modern8FurnitureCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100, verbose_name='Category Type Title')),
                ('category_slug', models.SlugField(help_text='e.g., luxury-chairs, modern-sofas', max_length=120)),
            ],
            options={
                'verbose_name': 'modern8 Furniture Category Slot',
                'verbose_name_plural': 'modern8 Furniture Category Slots',
            },
        ),
        migrations.CreateModel(
            name='Modern8FurnitureStoreFront',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studio_email', models.EmailField(default='hello@furni.corex.ng', max_length=254)),
                ('studio_hotline', models.CharField(default='+234 (0) 900 800 7000', max_length=30)),
                ('studio_showroom_address', models.CharField(default='Block 12, Admiralty Way, Lekki Phase 1, Lagos, Nigeria', max_length=255)),
                ('studio_logo', models.ImageField(blank=True, null=True, upload_to='modern8_studio_logos/')),
                ('hero_headline_title', models.CharField(default='Modern Interior Design Studio', max_length=255)),
                ('hero_subhead_copy', models.TextField(default='Donec vitae odio quis nisl dapibus malesuada. Nullam ac aliquet velit.')),
                ('hero_banner_image', models.ImageField(blank=True, null=True, upload_to='modern8_studio_heros/')),
                ('about_headline', models.CharField(default='Crafted with excellent material.', max_length=255)),
                ('about_description_copy', models.TextField(default='Donec vitae odio quis nisl dapibus malesuada. Nullam ac aliquet velit.')),
                ('about_showcase_thumbnail', models.ImageField(blank=True, null=True, upload_to='modern8_about/')),
                ('initialized_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'modern8 Furniture Store Profile',
                'verbose_name_plural': 'modern8 Furniture Store Profiles',
                'ordering': ['-initialized_at'],
            },
        ),
        migrations.CreateModel(
            name='Modern8FurnitureProductListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_title', models.CharField(max_length=150, verbose_name='Product Item Title')),
                ('price_numeric', models.DecimalField(decimal_places=2, default=50000.0, help_text='Set your retail price tag', max_digits=12)),
                ('product_thumbnail', models.ImageField(help_text='Upload crisp product picture', upload_to='modern8_products/')),
                ('product_details_text', models.TextField(default='Premium design crafted with elite wood types and materials.')),
                ('is_in_stock', models.BooleanField(default=True, verbose_name='Available for Dispatch')),
                ('is_featured_on_home', models.BooleanField(default=False, verbose_name='Showcase in Home Slider Aisle')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dynamic_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='listed_furniture', to='modern8.modern8furniturecategory', verbose_name='Furniture Type Category')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studio_products', to='modern8.modern8furniturestorefront')),
            ],
            options={
                'verbose_name': 'modern8 Furniture Product Listing Card',
                'verbose_name_plural': 'modern8 Furniture Product Listing Cards',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='modern8furniturecategory',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studio_categories', to='modern8.modern8furniturestorefront'),
        ),
        migrations.CreateModel(
            name='Modern8FurnitureBlogArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_title', models.CharField(max_length=250, verbose_name='Article Title')),
                ('author_display_name', models.CharField(default='', max_length=100)),
                ('article_thumbnail', models.ImageField(upload_to='modern8_blogs/')),
                ('published_date', models.DateField(auto_now_add=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studio_blogs', to='modern8.modern8furniturestorefront')),
            ],
            options={
                'verbose_name': 'modern8 Studio Blog Post',
                'verbose_name_plural': 'modern8 Studio Blog Posts',
                'ordering': ['-published_date'],
            },
        ),
        migrations.CreateModel(
            name='Modern8FurnitureTenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studio_name', models.CharField(max_length=120, unique=True, verbose_name='Furniture Studio Name')),
                ('studio_slug', models.SlugField(help_text='e.g., premium-furni, luxury-living', max_length=120, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User Account')),
            ],
            options={
                'verbose_name': 'modern8 Furniture Tenant',
                'verbose_name_plural': 'modern8 Furniture Tenants',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='modern8furniturestorefront',
            name='tenant_identity',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='studio_profile', to='modern8.modern8furnituretenant', verbose_name='SaaS Identity Link'),
        ),
        migrations.CreateModel(
            name='Modern8NewsletterSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscriber_name', models.CharField(max_length=120)),
                ('subscriber_email', models.EmailField(max_length=254)),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studio_subscribers', to='modern8.modern8furniturestorefront')),
            ],
            options={
                'verbose_name': 'modern8 Newsletter Lead',
                'verbose_name_plural': 'modern8 Newsletter Leads',
                'ordering': ['-subscribed_at'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='modern8furniturecategory',
            unique_together={('store', 'category_slug')},
        ),
    ]
