# Generated by Django 6.1 on 2026-09-14 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modern8', '0001_initial'),
        ('super_admin', '0009_domainengine'),
    ]

    operations = [
        migrations.AddField(
            model_name='modern8furnituretenant',
            name='assigned_agent',
            field=models.ForeignKey(blank=True, help_text='The field agent tracking this premium furniture profile registry', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modern8_onboarded_studios', to='super_admin.agentprofile', verbose_name='Assigned Agent'),
        ),
    ]
