# Generated by Django 6.1 on 2026-09-15 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modern8', '0002_modern8furnituretenant_assigned_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='modern8furniturestorefront',
            name='pillar_1_copy',
            field=models.TextField(default='Donec vitae odio quis nisl dapibus malesuada. Nullam ac aliquet velit.'),
        ),
        migrations.AddField(
            model_name='modern8furniturestorefront',
            name='pillar_1_title',
            field=models.CharField(default='Fast & Free Shipping', max_length=100),
        ),
        migrations.AddField(
            model_name='modern8furniturestorefront',
            name='pillar_2_copy',
            field=models.TextField(default='Donec vitae odio quis nisl dapibus malesuada. Nullam ac aliquet velit.'),
        ),
        migrations.AddField(
            model_name='modern8furniturestorefront',
            name='pillar_2_title',
            field=models.CharField(default='Easy to Shop', max_length=100),
        ),
        migrations.AddField(
            model_name='modern8furniturestorefront',
            name='pillar_3_copy',
            field=models.TextField(default='Donec vitae odio quis nisl dapibus malesuada. Nullam ac aliquet velit.'),
        ),
        migrations.AddField(
            model_name='modern8furniturestorefront',
            name='pillar_3_title',
            field=models.CharField(default='24/7 Support', max_length=100),
        ),
        migrations.AddField(
            model_name='modern8furniturestorefront',
            name='pillar_4_copy',
            field=models.TextField(default='Donec vitae odio quis nisl dapibus malesuada. Nullam ac aliquet velit.'),
        ),
        migrations.AddField(
            model_name='modern8furniturestorefront',
            name='pillar_4_title',
            field=models.CharField(default='Hassle Free Returns', max_length=100),
        ),
        migrations.AddField(
            model_name='modern8furniturestorefront',
            name='why_choose_us_intro',
            field=models.TextField(default='Donec vitae odio quis nisl dapibus malesuada. Nullam ac aliquet velit.', verbose_name='Why Choose Us Description'),
        ),
        migrations.CreateModel(
            name='Modern8FurnitureTestimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100, verbose_name='Client Name')),
                ('client_role', models.CharField(help_text='e.g., CEO, Co-Founder, XYZ Inc.', max_length=120, verbose_name='Designation/Company')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='modern8_avatars/', verbose_name='User Avatar')),
                ('quote', models.TextField(verbose_name='Testimonial Quote Statement')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studio_testimonials', to='modern8.modern8furniturestorefront')),
            ],
            options={
                'verbose_name': 'modern8 Furniture Testimonial',
                'verbose_name_plural': 'modern8 Furniture Testimonials',
            },
        ),
        migrations.CreateModel(
            name='Modern8StudioTeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_name', models.CharField(max_length=120, verbose_name='Full Name')),
                ('member_role', models.CharField(help_text='e.g., CEO, Founder, Senior Decorator', max_length=120, verbose_name='Corporate Designation')),
                ('member_avatar', models.ImageField(upload_to='modern8_team/', verbose_name='Profile Picture')),
                ('member_bio_short', models.TextField(default='Separated they live in Bookmarksgrove right at the coast of the Semantics.', verbose_name='Short Biography')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studio_team_members', to='modern8.modern8furniturestorefront')),
            ],
            options={
                'verbose_name': 'modern8 Studio Team Member Card',
                'verbose_name_plural': 'modern8 Studio Team Member Cards',
            },
        ),
    ]
