# Generated by Django 6.1 on 2026-09-15 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modern8', '0003_modern8furniturestorefront_pillar_1_copy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modern8furniturestorefront',
            name='service_pillar_1_copy',
            field=models.TextField(default='Get your furniture delivered to your door quickly without any extra delivery fees.'),
        ),
        migrations.AddField(
            model_name='modern8furniturestorefront',
            name='service_pillar_1_title',
            field=models.CharField(default='Fast & Free Shipping', max_length=100),
        ),
        migrations.AddField(
            model_name='modern8furniturestorefront',
            name='service_pillar_2_copy',
            field=models.TextField(default='Browse through our showroom catalog online and select your items with ease.'),
        ),
        migrations.AddField(
            model_name='modern8furniturestorefront',
            name='service_pillar_2_title',
            field=models.CharField(default='Easy to Shop', max_length=100),
        ),
        migrations.AddField(
            model_name='modern8furniturestorefront',
            name='service_pillar_3_copy',
            field=models.TextField(default='Our dedicated sales team is always active to answer all your inquiries instantly.'),
        ),
        migrations.AddField(
            model_name='modern8furniturestorefront',
            name='service_pillar_3_title',
            field=models.CharField(default='24/7 Support', max_length=100),
        ),
        migrations.AddField(
            model_name='modern8furniturestorefront',
            name='service_pillar_4_copy',
            field=models.TextField(default='Enjoy peace of mind with our stress-free return policy if items do not match.'),
        ),
        migrations.AddField(
            model_name='modern8furniturestorefront',
            name='service_pillar_4_title',
            field=models.CharField(default='Hassle Free Returns', max_length=100),
        ),
        migrations.AddField(
            model_name='modern8furniturestorefront',
            name='service_pillar_5_copy',
            field=models.TextField(default='We build unique furniture tailored specifically to your exact home dimensions.'),
        ),
        migrations.AddField(
            model_name='modern8furniturestorefront',
            name='service_pillar_5_title',
            field=models.CharField(default='Custom Fabrication', max_length=100),
        ),
        migrations.AddField(
            model_name='modern8furniturestorefront',
            name='service_pillar_6_copy',
            field=models.TextField(default='Our design architects help choose materials and maximize your room layout efficiency.'),
        ),
        migrations.AddField(
            model_name='modern8furniturestorefront',
            name='service_pillar_6_title',
            field=models.CharField(default='Interior Consults', max_length=100),
        ),
        migrations.AddField(
            model_name='modern8furniturestorefront',
            name='service_pillar_7_copy',
            field=models.TextField(default='Our direct team handles unpacking, fitting, and complete installation at your site.'),
        ),
        migrations.AddField(
            model_name='modern8furniturestorefront',
            name='service_pillar_7_title',
            field=models.CharField(default='Premium Assembly', max_length=100),
        ),
        migrations.AddField(
            model_name='modern8furniturestorefront',
            name='service_pillar_8_copy',
            field=models.TextField(default='Rest easy knowing all structural materials come with premium protective coverage.'),
        ),
        migrations.AddField(
            model_name='modern8furniturestorefront',
            name='service_pillar_8_title',
            field=models.CharField(default='Lifetime Warranty', max_length=100),
        ),
    ]
