# Generated by Django 6.1 on 2026-09-08 11:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('super_admin', '0008_platformsetting_server_state_eight_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Modern7CourseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(help_text='e.g., Software Engineering, Digital Marketing', max_length=100, verbose_name='Category Group Name')),
                ('category_slug', models.SlugField(help_text="e.g., 'software-eng' or 'marketing'", max_length=120, verbose_name='Filter URL Slug Token')),
                ('category_icon', models.ImageField(blank=True, null=True, upload_to='modern7/categories/', verbose_name='Small Dynamic Roster Icon Graphic')),
            ],
            options={
                'verbose_name': 'modern7 Course Category',
                'verbose_name_plural': 'modern7 Course Categories',
            },
        ),
        migrations.CreateModel(
            name='Modern7FacultyInstructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='Instructor Full Name')),
                ('professional_title', models.CharField(default='Senior Web Lecturer', max_length=150, verbose_name='Faculty Professional Title Designation')),
                ('profile_avatar', models.ImageField(blank=True, null=True, upload_to='modern7/instructors/', verbose_name='Teacher Profile Card Portrait Picture')),
                ('biography_summary', models.TextField(verbose_name='Teacher Short Bio Resume Profile')),
                ('count_courses_text', models.CharField(default='04 Courses', max_length=50, verbose_name='Teacher Card Metric: Active Classes Count')),
                ('count_students_text', models.CharField(default='27 Students', max_length=50, verbose_name='Teacher Card Metric: Active Student Pool')),
                ('twitter_url', models.URLField(blank=True, null=True, verbose_name='Teacher X Account URL Link')),
                ('facebook_url', models.URLField(blank=True, null=True, verbose_name='Teacher Facebook Account URL Link')),
                ('linkedin_url', models.URLField(blank=True, null=True, verbose_name='Teacher LinkedIn Account URL Link')),
            ],
            options={
                'verbose_name': 'modern7 Faculty Instructor',
                'verbose_name_plural': 'modern7 Faculty Instructors',
            },
        ),
        migrations.CreateModel(
            name='Modern7CourseListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_title', models.CharField(max_length=255, verbose_name='Course Title Heading Name')),
                ('course_thumbnail', models.ImageField(upload_to='modern7/courses/', verbose_name='High-Res Course Feature Cover Picture Image')),
                ('course_description_main', models.TextField(verbose_name='Primary Core Introduction Description Paragraph Copy')),
                ('course_description_secondary', models.TextField(verbose_name='Secondary Structural Curriculum Description Paragraph Copy')),
                ('course_overview_text', models.TextField(blank=True, null=True, verbose_name='Interactive Overview Tab Main Content Copy')),
                ('curriculum_syllabus_text', models.TextField(blank=True, help_text='Write out your module outlines using paragraphs or list nodes cleanly.', null=True, verbose_name='Curriculum Syllabus Syllabus Tab Rich Text (HTML Allowed)')),
                ('duration_label', models.CharField(default='2 Hrs 30 Min', max_length=100, verbose_name='Lecture Duration Specs String (e.g. 10 weeks, 4 Hrs)')),
                ('count_modules_text', models.CharField(default='12 Lectures', max_length=100, verbose_name='Total Training Modules String (e.g. 45 Classes)')),
                ('count_students_registered', models.CharField(default='1,000+ Enrolled', max_length=50, verbose_name='Card Indicator: Enrolled Capacity Number String')),
                ('seats_available', models.IntegerField(default=30, verbose_name='Open Registration Seats Available Capacity')),
                ('price_display_label', models.CharField(default='$99', max_length=60, verbose_name='Course Fee Price Display Text Label (e.g. $49, Free)')),
                ('is_certified', models.BooleanField(default=True, verbose_name='Provides Professional Certification Stamps Upon Graduation')),
                ('embed_video_url_id', models.CharField(blank=True, help_text="Provide ONLY the 11-character video ID from the URL code block text. e.g. 'RXv_uIN6e-Y'", max_length=100, null=True, verbose_name='YouTube Trailer Video Video ID String Only')),
                ('is_visible_on_catalog', models.BooleanField(default=True, verbose_name='Visible on School storefront Roster View')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('dynamic_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='category_courses', to='modern7.modern7coursecategory', verbose_name='Category Target Bucket Link')),
                ('assigned_instructor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instructor_courses', to='modern7.modern7facultyinstructor', verbose_name='Assigned Lecturer Node')),
            ],
            options={
                'verbose_name': 'modern7 Course Listing',
                'verbose_name_plural': 'modern7 Course Listings',
            },
        ),
        migrations.CreateModel(
            name='Modern7CourseReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=150, verbose_name='Student Reviewer Name')),
                ('student_email', models.EmailField(max_length=254, verbose_name='Student Verification Email Address')),
                ('rating_score', models.IntegerField(default=5, verbose_name='Star Review Score Metric (1-5 Rating)')),
                ('feedback_comment_text', models.TextField(verbose_name='Review Feedback Text Comment Body Copy Description')),
                ('is_approved_for_public', models.BooleanField(default=True, verbose_name='Approved to Stream on Public View Frontboards')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('target_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_reviews', to='modern7.modern7courselisting', verbose_name='Target Lecture Class Node')),
            ],
            options={
                'verbose_name': 'modern7 Student Course Review',
                'verbose_name_plural': 'modern7 Student Course Reviews',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Modern7SchoolTenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(help_text='e.g., Apex Tech University, Lagos Coding Academy', max_length=150, unique=True, verbose_name='Institution Name')),
                ('slug_path', models.SlugField(help_text="The URL path text. e.g., 'apex-tech' or 'lca' (all lowercase)", max_length=150, unique=True, verbose_name='Unique School URL Slug')),
                ('is_active_node', models.BooleanField(default=True, help_text='Turn off to instantly lock down or suspend this entire school tenant website.', verbose_name='Operational Status Switch')),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('onboarding_agent', models.ForeignKey(blank=True, help_text='The field agent tracking this custom campus account profile history', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modern7_onboarded_schools', to='super_admin.agentprofile')),
                ('owner_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modern7_schools', to=settings.AUTH_USER_MODEL, verbose_name='School Administrator Account')),
            ],
            options={
                'verbose_name': 'modern7 School Tenant',
                'verbose_name_plural': 'modern7 School Tenants',
                'ordering': ['-registered_at'],
            },
        ),
        migrations.CreateModel(
            name='Modern7PlatformConfigDeck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution_name', models.CharField(default='Eduleb Academy', max_length=200, verbose_name='Public Branding Name')),
                ('brand_logo', models.ImageField(blank=True, null=True, upload_to='modern7/logos/', verbose_name='Navbar Brand Logo')),
                ('footer_summary_text', models.TextField(default='Premium educational multi-tenant learning framework dedicated to structuring high-value conceptual mastery modules.', verbose_name='Footer Short Bio Paragraph')),
                ('support_phone', models.CharField(default='+234 700 900 8888', max_length=40, verbose_name='Direct Phone Hotline')),
                ('whatsapp_number', models.CharField(default='2347009008888', max_length=40, verbose_name='WhatsApp Business Digit Tracker (No spaces/plus)')),
                ('support_email', models.EmailField(default='registrar@campus-node.edu.ng', max_length=254, verbose_name='Public Admissions Mailbox')),
                ('office_address', models.TextField(default='Block 14, Admiralty Way, Lekki Phase 1, Lagos, Nigeria', verbose_name='Physical Facility Address')),
                ('google_map_embed_iframe', models.TextField(blank=True, help_text='Paste your direct Google Maps share iframe tag node row block safely here.', null=True, verbose_name='Google Map Embed Code (Iframe script)')),
                ('hero_tagline_accent', models.CharField(default='Smart Study', max_length=100, verbose_name='Hero Tagline Callout Accent')),
                ('hero_main_title', models.CharField(default='Where Knowledge Meets the Web', max_length=255, verbose_name='Hero Typography Main Title')),
                ('hero_description_text', models.TextField(default='We offer a brand new approach to the most basic learning paradigms. Choose from a wide range of learning options and gain new skills!', verbose_name='Hero Content Overview text')),
                ('hero_background', models.ImageField(blank=True, null=True, upload_to='modern7/hero/', verbose_name='Landing Cockpit Background Frame Image')),
                ('hero_side_illustration', models.ImageField(blank=True, null=True, upload_to='modern7/hero/', verbose_name='Hero Right Side Illustration Graphic Banner')),
                ('count_active_students', models.CharField(default='4,500+', max_length=30, verbose_name='Metrics Tracker: Student Count')),
                ('count_online_courses', models.CharField(default='134', max_length=30, verbose_name='Metrics Tracker: Class Total Count')),
                ('count_academic_programs', models.CharField(default='299', max_length=30, verbose_name='Metrics Tracker: Programs Total Count')),
                ('count_certified_students', models.CharField(default='684', max_length=30, verbose_name='Metrics Tracker: Certified Alumni Count')),
                ('count_enrolled_students', models.CharField(default='941', max_length=30, verbose_name='Metrics Tracker: Total Lifetime Registrations')),
                ('features_title', models.CharField(default='Start your journey With us', max_length=255, verbose_name='Journey Matrix Section Heading')),
                ('features_summary', models.TextField(default='We offer a brand new approach to the most basic learning paradigms. Choose from a wide range of learning options and gain new skills!', verbose_name='Journey Section Summary Text Copy')),
                ('feat_one_title', models.CharField(default='Expert <br />Teachers', max_length=150, verbose_name='Feature 1 Typography Title')),
                ('feat_one_desc', models.TextField(default='Lorem ipsum dolor sit amet, consectetur notted adipisicing elit ut labore.', verbose_name='Feature 1 description info text')),
                ('feat_two_title', models.CharField(default='Quality <br />Education', max_length=150, verbose_name='Feature 2 Typography Title')),
                ('feat_two_desc', models.TextField(default='Lorem ipsum dolor sit amet, consectetur notted adipisicing elit ut labore.', verbose_name='Feature 2 description info text')),
                ('feat_three_title', models.CharField(default='Remote <br />Learning', max_length=150, verbose_name='Feature 3 Typography Title')),
                ('feat_three_desc', models.TextField(default='Lorem ipsum dolor sit amet, consectetur notted adipisicing elit ut labore.', verbose_name='Feature 3 description info text')),
                ('feat_four_title', models.CharField(default='Life Time <br />Support', max_length=150, verbose_name='Feature 4 Typography Title')),
                ('feat_four_desc', models.TextField(default='Lorem ipsum dolor sit amet, consectetur notted adipisicing elit ut labore.', verbose_name='Feature 4 description info text')),
                ('about_illustration', models.ImageField(blank=True, null=True, upload_to='modern7/about/', verbose_name='About Panel Presentation Artwork Graphic')),
                ('about_headline_title', models.CharField(default='We Are Providing The Online Course In Global World', max_length=255, verbose_name='About Section Title Typography Header')),
                ('about_description_one', models.TextField(default='We offer a brand new approach to the most basic learning paradigms. Choose from a wide range of learning options and gain new skills!', verbose_name='About Summary Description Column 1')),
                ('about_description_two', models.TextField(default='Our multi-tenant school parameters ensure professional-grade operational integrity at absolute zero wait system lag times.', verbose_name='About Summary Description Column 2')),
                ('about_bullet_one', models.CharField(default='Get access to <b>12,000+</b> of our top courses', max_length=255, verbose_name='About Bullet Highlight line 1')),
                ('about_bullet_two', models.CharField(default='Popular topic to learn now in our online courses for student', max_length=255, verbose_name='About Bullet Highlight line 2')),
                ('about_bullet_three', models.CharField(default='Find the right instructor for you', max_length=255, verbose_name='About Bullet Highlight line 3')),
                ('twitter_x_url', models.URLField(default='https://x.com', verbose_name='X / Twitter Tracking Account Link')),
                ('facebook_url', models.URLField(default='https://facebook.com', verbose_name='Facebook Tracking Account Link')),
                ('instagram_url', models.URLField(default='https://instagram.com', verbose_name='Instagram Tracking Account Link')),
                ('linkedin_url', models.URLField(default='https://linkedin.com', verbose_name='LinkedIn Tracking Account Link')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_link', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='visual_config', to='modern7.modern7schooltenant', verbose_name='School Profile Anchor')),
            ],
            options={
                'verbose_name': 'modern7 Custom View Configuration',
                'verbose_name_plural': 'modern7 Custom View Configurations',
            },
        ),
        migrations.AddField(
            model_name='modern7facultyinstructor',
            name='school_tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campus_instructors', to='modern7.modern7schooltenant', verbose_name='School Context Anchor'),
        ),
        migrations.AddField(
            model_name='modern7courselisting',
            name='school_tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campus_courses', to='modern7.modern7schooltenant', verbose_name='School Context Anchor'),
        ),
        migrations.AddField(
            model_name='modern7coursecategory',
            name='school_tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_categories', to='modern7.modern7schooltenant', verbose_name='School Context Anchor'),
        ),
        migrations.CreateModel(
            name='Modern7StudentEnquiryLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=150, verbose_name='Student Applicant Name')),
                ('client_email', models.EmailField(max_length=254, verbose_name='Student Communication Mailbox Address')),
                ('lead_subject', models.CharField(max_length=255, verbose_name='Message Subject Title Track')),
                ('message_content', models.TextField(verbose_name='Applicant Enquiry Message Content text Body')),
                ('is_processed_flag', models.BooleanField(default=False, verbose_name='Admissions Registrar Processed Status Indicator Mark')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('school_tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_leads', to='modern7.modern7schooltenant', verbose_name='School Context Anchor')),
            ],
            options={
                'verbose_name': 'modern7 Contact Enquiry Lead',
                'verbose_name_plural': 'modern7 Contact Enquiry Leads',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='modern7coursecategory',
            unique_together={('school_tenant', 'category_slug')},
        ),
    ]
